# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
# [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
# Embedded file name: types.py
from types import *
CONNECT_USING_PORT = 0
CONNECT_USING_HANDLE = 1
DATA_PARITY_NONE = 0
DATA_PARITY_ODD = 1
DATA_PARITY_EVEN = 2
DATA_PARITY_MARK = 3
DATA_PARITY_SPACE = 4
STOP_BITS_ONE = 0
STOP_BITS_ONE_POINT_FIVE = 1
STOP_BITS_TWO = 2
STATUS_EXIT = 0
STATUS_CONNECTED = 1
STATUS_DISCONNECTED = 2
STATUS_DATA_RECEIVED = 3
STATUS_DATA_WRITTEN = 4
STATUS_DATA_WRITE_FAILURE = 5
CONNECT_RESULT_SUCCESS = MCL_TRUE
CONNECT_RESULT_FAILURE = MCL_FALSE