# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
# [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
# Embedded file name: eventlog_edit.py
ERR_EVENT_LOG_EDIT_SUCCESS = 0
ERR_EVENT_LOG_EDIT_LOADLIBRARY = 1
ERR_EVENT_LOG_EDIT_GETPROCADDRESS = 2
ERR_EVENT_LOG_EDIT_ADDRESSNOTFOUND = 3
ERR_EVENT_LOG_EDIT_FILESIZEERROR = 4
ERR_EVENT_LOG_EDIT_RESOURCELOCKFAILURE = 5
ERR_EVENT_LOG_EDIT_SETFILEPOINTER = 6
ERR_EVENT_LOG_EDIT_LOGFILECORRUPT = 7
ERR_EVENT_LOG_EDIT_RECORDTOOLARGE = 8
ERR_EVENT_LOG_EDIT_EXCEPTIONTHROWN = 9
ERR_EVENT_LOG_EDIT_INVALID_RECORD_NUMBER = 10
ERR_EVENT_LOG_EDIT_GET_LOG_FAILED = 11
ERR_EVENT_LOG_EDIT_INJECTION_SETUP_FAILED = 12
ERR_EVENT_LOG_EDIT_OPEN_PROCESS_FAILED = 13
ERR_EVENT_LOG_EDIT_INVALID_PARAMETER = 14
ERR_EVENT_LOG_EDIT_MALLOC_FAILED = 15
ERR_EVENT_LOG_EDIT_ATOMNOTFOUND = 16
ERR_EVENT_LOG_EDIT_ATOMMATCHNOTFOUND = 17
ERR_EVENT_LOG_EDIT_INJECTION_FAILED = 18
ERR_EVENT_LOG_EDIT_COULD_NOT_FIND_FILE = 19
errorStrings = {ERR_EVENT_LOG_EDIT_LOADLIBRARY: 'LoadLibrary failed within injected code',
   ERR_EVENT_LOG_EDIT_GETPROCADDRESS: 'GetProcAddress failed within injected code',
   ERR_EVENT_LOG_EDIT_ADDRESSNOTFOUND: 'Injection Code unable to find usable address',
   ERR_EVENT_LOG_EDIT_FILESIZEERROR: 'ViewSize does not match ActualMaxFileSize',
   ERR_EVENT_LOG_EDIT_RESOURCELOCKFAILURE: 'Failed to obtain resource lock for requested log file',
   ERR_EVENT_LOG_EDIT_SETFILEPOINTER: 'SetFilePointer failed within injected code',
   ERR_EVENT_LOG_EDIT_LOGFILECORRUPT: 'Logfile is corrupt',
   ERR_EVENT_LOG_EDIT_RECORDTOOLARGE: 'Record too large to delete',
   ERR_EVENT_LOG_EDIT_EXCEPTIONTHROWN: 'Injected code threw an exception',
   ERR_EVENT_LOG_EDIT_INVALID_RECORD_NUMBER: 'Record number not found within given log',
   ERR_EVENT_LOG_EDIT_GET_LOG_FAILED: 'Failed to get location of log file',
   ERR_EVENT_LOG_EDIT_INJECTION_SETUP_FAILED: 'Setup for injection failed',
   ERR_EVENT_LOG_EDIT_OPEN_PROCESS_FAILED: 'Open of services.exe process failed',
   ERR_EVENT_LOG_EDIT_INVALID_PARAMETER: 'Invalid parameter(s)',
   ERR_EVENT_LOG_EDIT_MALLOC_FAILED: 'Failed to malloc memory',
   ERR_EVENT_LOG_EDIT_ATOMNOTFOUND: 'ATOM value not found',
   ERR_EVENT_LOG_EDIT_ATOMMATCHNOTFOUND: 'No ATOM match was found',
   ERR_EVENT_LOG_EDIT_INJECTION_FAILED: 'Injection Create Remote Thread failed',
   ERR_EVENT_LOG_EDIT_COULD_NOT_FIND_FILE: 'Unable to find matching file'
   }