# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
# [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
# Embedded file name: tasking.py
import mcl_platform.tasking
from tasking_dsz import *
from tasking_ur import *
_fw = mcl_platform.tasking.GetFramework()
if _fw == 'dsz':
    RPC_INFO_LIST_DRIVERS = dsz.RPC_INFO_LIST_DRIVERS
    RPC_INFO_LIST_DATASOURCES = dsz.RPC_INFO_LIST_DATASOURCES
    RPC_INFO_CONNECT = dsz.RPC_INFO_CONNECT
    RPC_INFO_LIST_SERVERS = dsz.RPC_INFO_LIST_SERVERS
    RPC_INFO_LIST_DATABASES = dsz.RPC_INFO_LIST_DATABASES
    RPC_INFO_LIST_TABLES = dsz.RPC_INFO_LIST_TABLES
    RPC_INFO_LIST_COLUMNS = dsz.RPC_INFO_LIST_COLUMNS
    RPC_INFO_EXEC = dsz.RPC_INFO_EXEC
    RPC_INFO_LIST_HANDLES = dsz.RPC_INFO_LIST_HANDLES
    RPC_INFO_DISCONNECT = dsz.RPC_INFO_DISCONNECT
elif _fw == 'ur':
    RPC_INFO_DISCONNECT = ur.RPC_INFO_DISCONNECT
    RPC_INFO_EXEC = ur.RPC_INFO_EXEC
    RPC_INFO_LIST_COLUMNS = ur.RPC_INFO_LIST_COLUMNS
    RPC_INFO_LIST_DATASOURCES = ur.RPC_INFO_LIST_DATASOURCES
    RPC_INFO_LIST_SERVERS = ur.RPC_INFO_LIST_SERVERS
    RPC_INFO_LIST_DRIVERS = ur.RPC_INFO_LIST_DRIVERS
    RPC_INFO_LIST_DATABASES = ur.RPC_INFO_LIST_DATABASES
    RPC_INFO_LIST_TABLES = ur.RPC_INFO_LIST_TABLES
    RPC_INFO_LIST_HANDLES = ur.RPC_INFO_LIST_HANDLES
    RPC_INFO_CONNECT = ur.RPC_INFO_CONNECT
else:
    raise RuntimeError('Unsupported framework (%s)' % _fw)