# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
# [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
# Embedded file name: diba_errors.py
DB_SUCCESS = 0
DB_FAILURE = 1
DB_LOGGER_INIT_FAILED = 2
DB_COULD_NOT_INTIALIZE_API = 3
DB_INVALID_PARAMETER = 4
DB_LOGGER_SHUTDOWN_FAILED = 5
DB_ERROR_KS_COMMUNICATIONS = 6
DB_ARCHIVE_FAILED = 7
DB_INSUFFICIENT_MEMORY = 8
DB_INSUFFICIENT_BUFFER = 9
DB_NO_ENTRIES = 10
DB_CLEANUP_NATIVEAPI_FAILED = 11
DB_ABANDON_ARCHIVE_FAILED = 12
DB_ABANDON_ARCHIVE_LOGGER_SHUTDOWN_FAILED = 13
DB_ABANDON_ARCHIVE_CLEANUP_NATIVE_API_FAILED = 14
DB_CLEANUP_NATIVE_API_LOGGER_SHUTDOWN_FAILED = 15
DB_ABANDON_ARCHIVE_CLEANUP_NATIVE_API_LOGGER_SHUTDOWN_FAILED = 16
DB_FILE_ALREADY_EXISTS = 17
DB_TIMEOUT = 18
DB_ABANDONED = 19
DB_NO_DRIVER_REGISTRY_KEYS = 20
DB_VALUE_NOT_FOUND = 21
DB_ACCESS_DENIED = 22
DB_INCOMPATIBLE_VERSION = 23
DB_RESOURCE_NOT_FOUND = 24
DB_KS_COMMS_ALREADY_INITIALIZED = 25
DB_KS_INSTANCE_ALREADY_EXISTS = 26
DB_WINDOWS_DEFENDER_RESTORE_ERROR = 27
DB_REGISTRY_IO_FAILED = 28
DB_NAME_NOT_FOUND = 29
DB_KS_INIT_FAILED = 30
DB_DWBH_INIT_FAILED = 201
DB_ST_OS_NOT_SUPPORTED = 202
DB_ML_THUNK_DECRYPTION_FAILED = 203
DB_ML_THUNK_DATABASE_NOT_EMPTY = 204
DB_ST_FILESYSTEM_NOT_SUPPORTED = 205
DB_ST_MULTIBOOT = 206
DB_ST_EFI_NOT_SUPPORTED = 207
DB_ST_PACK_CONTAINER_FAILED = 208
DB_ST_UNPACK_CONTAINER_FAILED = 209
DB_ST_ALREADY_PRESENT = 210
DB_ML_THUNK_ALREADY_PRESENT = 211
DB_ST_EXTRACT_PACK_FAILED = 212
DB_ST_CANT_GET_VERSION = 213
DB_ST_NEWER_VERSION_PRESENT = 214
DB_KS_CACHE_ENTRY_INVALID = 215
DB_MLSTORE_UNSUPPORTED_VERSION = 221
DB_ST_UPGRADE_PERFORMED = 222
DB_ST_SOTI_IN_USE = 223
DB_ST_BITLOCKER_PRESENT = 224
DB_ST_FAILED_TO_OBTAIN_BITLOCKER_API = 225
DB_ST_BITLOCKER_API_CALL_FAILED = 226
DB_DRIVER_SIGNING_POLICY_BLOCKS_UNSIGNED = 227
DB_INCOMPATIBLE_PERSISTENCE_MECHANISM = 228
DB_LAUNCHER_DRIVER_NOT_SUPPORTED_ON_64_VISTA = 229
DB_ST_INSUFFICIENT_MEMORY = 230
DB_ST_UNPACK_CONTAINER_VALIDATION_1_FAILED = 231
DB_ST_UNPACK_CONTAINER_VALIDATION_2_FAILED = 232
DB_FAILED_TO_INIT_SYNCHRONIZATION_LOCK = 233
DB_TIMEOUT_WAITING_SYNCHRONIZATION_LOCK = 234
DB_FAILED_TO_ARCHIVE_EXISTING_SOTI_BEFORE_UNINSTALL = 235
DB_FAILED_TO_ARCHIVE_EXISTING_SOTI_BEFORE_UPGRADE = 236
DB_FAILED_TO_UNINSTALL_SOTI_AFTER_FAILED_ARCHIVE = 237
DB_FAILED_TO_ARCHIVE_EXISTING_KISU_BEFORE_UNINSTALL = 238
DB_KISU_UNINSTALL_FAILED = 239
DB_FAILED_TO_EXTRACT_DW_DRIVER = 240
DB_FAILED_TO_INIT_NATIVE_REGISTRY = 241
DB_FAILED_TO_EXTRACT_KISU_RESOURCES = 242
DB_KS_INSTALL_FAILED_TO_EXPAND_ENVIRONMENT_STRING = 243
DB_KS_INSTALL_FAILED_TO_CONSTRUCT_STRINGS = 244
DB_KS_INSTALL_FAILED_TO_WRITE_KSDRIVER_TO_REGISTRY = 245
DB_KS_INSTALL_FAILED_TO_WRITE_UML_TO_REGISTRY = 246
DB_KS_INSTALL_FAILED_TO_EDIT_LAUNCHER_THUNK_DATA = 247
DB_KS_INSTALL_FAILED_TO_REKEY_LAUNCHER_THUNK_DATA = 248
DB_KS_INSTALL_FAILED_TO_INSTALL_WITH_SUSC = 249
DB_KS_INSTALL_FAILED_TO_CREATE_LAUNCHER_THUNK_SUBKEY = 250
DB_KS_INSTALL_FAILED_TO_WRITE_LAUNCHER_THUNK_VALUE = 251
DB_KS_INSTALL_FAILED_TO_SET_SYSTEM_ROOT_VALUE = 252
DB_KS_INSTALL_FAILED_TO_CREATE_PROGRESS_SEMAPHORE = 253
DB_KS_INSTALL_FAILED_TO_START_LAUNCHER_DRIVER = 254
DB_KS_INSTALL_FAILED_TO_WRITE_KS_PERSISTENCE_ID = 255
DB_KS_INSTALL_FAILED_TO_WRITE_BH = 256
DB_KS_INSTALL_FAILED_TO_START_BH = 257
DB_KS_INSTALL_FAILED_TO_ARCHIVE_NEW_INSTALL = 258
DB_KS_INSTALL_FAILED_TO_CREATE_UML_TEMP_REG_KEY_NAME = 259
DB_KS_INSTALL_FAILED_TO_RETRIEVE_LAUNCHER_THUNK = 260
DB_KS_INSTALL_FAILED_TO_LOAD_KSDRIVER_VIA_DW = 261
DB_KS_INSTALL_FAILED_TO_UNMUNGE_KS_DRIVER = 262
DB_KS_INSTALL_FAILED_TO_UNCOMPRESS_KS_DRIVER = 263
DB_KS_INSTALL_FAILED_TO_FIND_SERVICE_KEYS = 264
DB_KS_INSTALL_FAILED_TO_ARCHIVE_EXISTING_MULTILAUNCHER = 265
DB_KS_INSTALL_FAILED_TO_ARCHIVE_NEW_MULTILAUNCHER = 266
DB_KS_INSTALL_FAILED_TO_CREATE_PARAMETERS_SUBKEY = 267
DB_KS_INSTALL_FAILED_TO_CREATE_LOGFILE_FOR_UML = 268
DB_KS_INSTALL_FAILED_TO_CREATE_LOGFILE_FOR_KSDRIVER = 269
DB_KS_INSTALL_FAILED_TO_FIND_KEYS_IN_USE_BY_KISU = 270
DB_KS_INSTALL_FAILED_TO_START_TRANSACTION = 271
DB_FAILED_TO_ARCHIVE_NEW_SOTI_AFTER_INSTALL = 272
DB_INIT_FAILED_TO_DETERMINE_IMAGE_BASE = 273
DB_GETPERPROCESSUNIQUEGUID_QUERY_BOOT_TIME_FAILED = 274
DB_GETPERPROCESSUNIQUEGUID_STRING_FORMAT_ERROR = 275
DB_GETPERPROCESSUNIQUEGUID_INVALID_PARAMETER = 276
DB_FAILED_TO_APPEND_TO_SYNCHRONIZATION_LOCK_GUID = 277
DB_LOGGINGINIT_PATH_ALLOCATION_ERROR = 278
DB_FAILED_TO_INIT_DIDE_CONFIG = 279
DB_FAILED_TO_ALLOCATE_MEMORY_FOR_DW_DRIVER = 280
DB_FAILED_TO_EXPAND_ENV_STRING_IN_LOG_PATH = 281
DB_FAILED_TO_CREATE_LOGFILE_DIRECTORY = 282
DB_FAILED_TO_SET_LOG_LEVEL = 283
DB_FAILED_TO_START_DIDE = 284
DB_SYNCHRONIZATION_OBJECT_ABANDONED = 285
DB_SYNCHRONIZATION_OBJECT_WAIT_FAILED = 286
DB_FAILED_TO_RELEASE_SYNCHRONIZATION_LOCK = 287
DB_LOGGING_GET_IMAGE_SIZE_FAILED = 288
DB_LOGGING_FAILED_TO_RETRIEVE_FILENAME_SALT = 289
DB_LOGGING_FAILED_TO_INIT_LOGWRITER = 290
DB_LOGGINGGETOVERRIDESFORIMAGE_INVALID_PARAM = 291
DB_KISU_PROGRESS_SEMAPHORE_NAME_COLLISION = 292
DB_FAILURE_GET_RESOURCE_INSUFFICIENT_MEMORY = 293
DB_FAILURE_GET_RESOURCE_INVALID_PARAMETER = 294
DB_FAILURE_GET_RESOURCE_FROM_NON_32BIT_BINARY = 295
DB_FAILURE_GET_RESOURCE_FROM_NON_64BIT_BINARY = 296
DB_FAILURE_GET_RESOURCE_INVALID_PE = 297
DB_FAILURE_GET_RESOURCE_SECTION_NOT_FOUND = 298
DB_FAILURE_GET_RESOURCE_PROP_DIR_NOT_FOUND = 299
DB_FAILURE_GET_RESOURCE_CANT_LOAD = 300
DB_FAILURE_GET_RESOURCE_CANT_GET_SIZE = 301
DB_FAILURE_GET_RESOURCE_CANT_LOCK = 302
DB_FAILURE_GET_RESOURCE_CANT_DECOMPRESS = 303
DB_EXISTING_MODULE_STORE_FOUND_WHEN_INSTALLING_KISU = 304
DB_KS_FAILED_TO_INIT_KSDATASTORE_LIB = 305
DB_KS_FAILED_TO_OPEN_DATASTORE = 306
DB_KS_MODULE_STORE_NOT_FOUND = 307
DB_KS_FAILED_TO_DESTROY_MODULE_STORE = 308
DB_KS_FAILED_INIT_USER_COMMS = 309
DB_KS_FAILED_INIT_NATIVE_API = 310
DB_KS_USERCOMMS_UNKNOWN_OJECT_VERSION = 311
DB_JUVI_OS_NOT_SUPPORTED = 312
DB_LAUNCHER_DRIVER_NOT_SUPPORTED_ON_NON64_WIN8 = 313
DB_ST_FAILED_UPGRADE_FAILED_ROLLBACK = 400
DB_ST_FAILED_UPGRADE_ROLLEDBACK = 401
DB_FAILURE_SECUREFILEDELETION_REOPENINGFILE_DELETEONCLOSE = 401
DB_FAILURE_SECUREFILEDELETION_REOPENINGFILE_OVERWRITE_TRUNCATE = 402
DB_FAILURE_SECUREFILEDELETION_COMPLETE_OVERWRITE_FILE = 403
DB_FAILURE_SECUREFILEDELETION_GETTING_LOWORDER_FILESIZE = 404
DB_FAILURE_SECUREFILEDELETION_GET_FILE_SIZE = 405
DB_FAILURE_SECUREFILEDELETION_GET_FILE_HANDLE = 406
DB_FAILURE_ABANDONARCHIVE_FLUSH = 410
DB_FAILURE_ROLLBACKARCHIVE_RESTORE = 411
DB_FAILURE_DEBUGMEMCHECKFORLEAKS_FOUNDLEAK = 415
DB_FAILURE_LOADDRIVER_LOAD = 420
DB_FAILURE_LOADDRIVER_ALREADYLOADED = 421
DB_FAILURE_LOADDRIVER_UNLOAD = 422
DB_FAILURE_UNLOADDRIVER_UNLOAD = 423
DB_FAILURE_UNLOADDRIVER_LOAD = 424
DB_FAILURE_STARTDRIVER_WITHSERVICENAME_PRINT_SERIVCEPATH = 425
DB_FAILURE_STOPDRIVER_WITHSERVICENAME_PRINT_SERVICEPATH = 426
DB_FAILURE_DISABLEWINDOWSDEFENDERRTP_QUERYREGISTRY = 427
DB_FAILURE_INSTALLDRIVER_DISABLEWINDOWSDEFENDER = 428
DB_FAILURE_INSTALLDRIVER_INSTALLFAILED = 429
DB_FAILURE_INSTALLDRIVER_INSTALLFAILED_REGISTRY_ENTRY = 430
DB_FAILURE_INSTALLDRIVER_INSTALLFAILED_DROP_FILE = 431
DB_FAILURE_INSTALLDRIVER_INSTALLFAILED_CANT_START = 432
DB_FAILURE_CONVERTPETIMETOFILETIME_SYSTEMTIME = 433
DB_FAILURE_GETIMAGETIMESTAMP_OPENFILE = 434
DB_FAILURE_GETIMAGETIMESTAMP_FILEHANDLE = 435
DB_FAILURE_GETIMAGETIMESTAMP_MAPSECTION = 436
DB_FAILURE_GETIMAGETIMESTAMP_MAP_INVALIDHANDLE = 437
DB_FAILURE_GETIMAGETIMESTAMP_GETPROCESS = 438
DB_FAILURE_GETIMAGETIMESTAMP_PROCESS_INVALID = 439
DB_FAILURE_GETIMAGETIMESTAMP_MAPVIEWOFSECTION = 440
DB_FAILURE_GETIMAGETIMESTAMP_MAPVIEW_INVALID = 441
DB_FAILURE_GETIMAGETIMESTAMP_TIMESTAMPGET = 442
DB_FAILURE_INSTALLDRIVERWITH_SUSC_IMAGETIMESTAMP_GET = 443
DB_FAILURE_INSTALLDRIVERWITH_SUSC_IMAGETIMESTAMP_SET = 444
DB_FAILURE_INSTALLDRIVERWITH_SUSC_FILEINFO_SAMPLE_GET = 445
DB_FAILURE_INSTALLDRIVERFROM_RESOURCEDEF_RESOURCESIZE_GET = 446
DB_FAILURE_INSTALLDRIVERFROM_RESOURCEDEF_PRINT_DRIVERNAME = 447
DB_FAILURE_INSTALLDRIVERFROM_RESOURCEDEF_INSTALLDRIVER = 448
DB_FAILURE_UNINSTALLDRIVER_PRINT_REGPATH = 449
DB_FAILURE_UNINSTALLDRIVER_REG_VALUE_GET = 450
DB_FAILURE_UNINSTALLDRIVER_UNINSTALL = 450
DB_FAILURE_UNINSTALLDRIVER_UNINSTALL_REGISTRY_ENTRY = 451
DB_FAILURE_UNINSTALLDRIVER_UNINSTALL_CANTERASEFILE = 452
DB_FAILURE_UNINSTALLDRIVER_UNINSTALL_CANTSTOP = 453
DB_FAILURE_UNINSTALLDRIVER_UNINSTALL = 454
DB_FAILURE_OPENEVENT_CREATE_EVENTHANDLE = 460
DB_FAILURE_OPENEVENT_ZWOPEN_UNKNOWN = 461
DB_FAILURE_SETEVENT_ZWSET_UNKNOWN = 462
DB_FAILURE_RESETEVENT_ZWRESET_UNKNOWN = 463
DB_FAILURE_WAITFORSINGLEOBJECT_UNKNOWN = 464
DB_FAILURE_CREATEEVENT_CREATEHANDLE = 465
DB_FAILURE_CREATEEVENT_INIT_SECURITY_DESC = 466
DB_FAILURE_CREATEEVENT_SET_SECURITY_DESC_DACL = 467
DB_FAILURE_CREATEEVENT_SET_SECURITY_OBJECT = 468
DB_FAILURE_CREATEEVENT_FAILED = 469
DB_FAILURE_SIMPLECREATE_CREATEFILEHANDLE = 475
DB_FAILURE_SIMPLECREATE_FAILED = 476
DB_FAILURE_GETFILESIZE_FAILED = 477
DB_FAILURE_SETSECURITYOBJ_FAILED = 478
DB_FAILURE_RENAMEFILE_FAILED = 479
DB_FAILURE_WRITEFILE_FAILED = 480
DB_FAILURE_READFILE_FAILED = 481
DB_FAILURE_FINDFILES_SNWPRINTF = 482
DB_FAILURE_FINDFILES_CREATEDIRHANDLE = 483
DB_FAILURE_FINDFILES_CREATEFILELISTHANDLE = 484
DB_FAILURE_FINDFILES_QUERYDIR = 485
DB_FAILURE_FINDFILES_FINDFILE = 486
DB_FAILURE_FINDFILES_UNEXPECTED = 487
DB_FAILURE_GETNEXTFILE_DATANULL = 488
DB_FAILURE_DRIVELETTER_OBJECTNAMEINFO = 489
DB_FAILURE_DRIVELETTER_OPENDIROBJ = 490
DB_FAILURE_DRIVELETTER_OPENSYMLINK = 491
DB_FAILURE_DRIVELETTER_FINDLOGICDRIVES = 492
DB_FAILURE_GETFILEINFO_GETFILEBASICINFO = 493
DB_FAILURE_GETFILEINFO_GETFILESTANDARDINFO = 494
DB_FAILURE_GETFILEINFO_GETFILENAMEINFO = 495
DB_FAILURE_SETFILEINFO_SETFILEENDINFO = 496
DB_FAILURE_SETFILEINFO_SETFILEBASICINFO = 497
DB_FAILURE_FILECLOSE_FAILURE = 498
DB_FAILURE_CRTFILEMAPPING_CREATEMAPHANDLE = 499
DB_FAILURE_CRTFILEMAPPING_INITSECURITYDESC = 500
DB_FAILURE_CRTFILEMAPPING_SETSECURITYDESCDACL = 501
DB_FAILURE_CRTFILEMAPPING_SETSECURITYOBJ = 502
DB_FAILURE_MAPVIEWFILE_OPENPROCESS = 503
DB_FAILURE_MAPVIEWFILE_MAPVIEWSECTION = 504
DB_FAILURE_UNMAPVIEWFILE_OPENPROCESS = 505
DB_FAILURE_UNMAPVIEWFILE_UNMAPVIEWSECTION = 504
DB_FAILURE_FILECLOSE_INVALIDTYPE = 505
DB_FAILURE_DELETE_FILE_SECURE_DELETE_FAILED = 506
DB_FAILURE_UNMAPVIEWFILE_UNMAPVIEWSECTION = 507
DB_FAILURE_FILECLOSE_INVALIDTYPE = 508
DB_FAILURE_SELFDEL_MODULEFILENAME = 510
DB_FAILURE_SELFDEL_PRINTPREFIX = 511
DB_FAILURE_SELFDEL_ASYNC_FILEDELETE = 512
DB_FAILURE_CLEANNATVIE_EXCEPT = 513
DB_FAILURE_KSINITCOMMS_NOSTATUS = 515
DB_FAILURE_KSSHUTDOWN_FAILED = 516
DB_FAILURE_KSWRITECOMPMUNGREGKEY_CREATEKEY = 517
DB_FAILURE_KSWRITECOMPMUNGREGKEY_COMPRESS = 518
DB_FAILURE_KSWRITECOMPMUNGREGKEY_MUNGE = 519
DB_FAILURE_KSWRITECOMPMUNGREGKEY_SAVEVALUE = 520
DB_FAILURE_KSWRITECOMPMUNGREGKEY_ALREADYMUNGCOMP = 521
DB_FAILURE_FINDMULTIKSSRVKEY_NOELIGIBLE = 522
DB_FAILURE_KSUNINSTALLST_PRINTTHUNKSVCNAME = 523
DB_FAILURE_KSUNINSTALLST_ARCHIVE = 524
DB_FAILURE_KSDELETEMOD_MODINFOSIZE = 525
DB_FAILURE_KSDELETEMOD_READMODINFO = 526
DB_FAILURE_KSDELETEMOD_MODDATASIZE = 527
DB_FAILURE_KSDELETEMOD_READMODDATA = 528
DB_FAILURE_KSDELETEMOD_ARCHIVEMOD = 529
DB_FAILURE_KSDELETEMOD_INSUFFICIENT_MEMORY = 530
DB_FAILURE_KSVERSION_FAILED = 531
DB_FAILURE_KSMODULEINFOLIST_LISTOBJECTSSIZE = 532
DB_FAILURE_KSMODULEINFOLIST_MODINFOLISTHANDLE = 533
DB_FAILURE_KSUNINSTALLPERSIST_INVALIDID = 534
DB_FAILURE_KSUNINSTALLINT_START_TRANSAC = 535
DB_FAILURE_KSUNINSTALLINT_CACHE_REMOVEKS = 536
DB_FAILURE_KSVALMODSTORE_MODSTOREDIRSIZE = 537
DB_FAILURE_KSVALMODSTORE_MODSTOREDIR = 538
DB_FAILURE_KSVALMODSTORE_MODSTOREDIR_DECRYPT = 539
DB_FAILURE_KSVALMODSTORE_MODSTOREDIRENTRYSIZE = 540
DB_FAILURE_KSVALMODSTORE_MODSTOREDIRENTRY = 541
DB_FAILURE_KSVALMODSTORE_MODSTOREDIRENTRY_DECRYPT = 542
DB_FAILURE_KSVALMODSTORE_COUNTVALUES = 543
DB_FAILURE_KSLOADMOD_FAILED = 544
DB_FAILURE_KSLOADMOD_ARCHIVE = 545
DB_FAILURE_KSSTARTSTOPDRIVER_ARCHIVE = 546
DB_FAILURE_REMOVEKSINSTANCEFROMCACHE = 550
DB_FAILURE_REMOVEKSINSTANCEFROMCACHE_EMPTY = 551
DB_FAILURE_FREEKSINSTANCEFROMCACHE = 552
DB_FAILURE_KSMODIDS_LISTOBJECTSSIZE = 553
DB_FAILURE_KSMODIDS_ALLOCATEMEM = 554
DB_FAILURE_KSMODIDS_REALLOCATEMEM = 555
DB_FAILURE_FINDKSINST_NOTFOUND = 556
DB_FAILURE_FINDKSINST_UCGETUMLFUNC = 557
DB_FAILURE_WAITKSINST_WAITSINGLEOBJ_SIGNAL = 558
DB_FAILURE_WAITKSINST_WAITSINGLEOBJ_THREAD = 559
DB_FAILURE_WAITKSINST_WAITSINGLEOBJ_EXITCODE = 560
DB_FAILURE_ENUMKSINST_WAIT = 561
DB_FAILURE_CFGDM2_VERCFG = 562
DB_FAILURE_CFGDM2_BUFOVERFLOW = 563
DB_FAILURE_KSINITCOMMSINT_FIND = 564
DB_FAILURE_KSINITCOMMSINT_CREATEVENT = 565
DB_FAILURE_KSINITCOMMSINT_SIGNALTHREAD = 566
DB_FAILURE_KSCFGINT_POPULATE = 567
DB_FAILURE_FLAGKS_PROCESSHANDLE = 568
DB_FAILURE_FLAGKS_PROCESSHANDLEINVALID = 569
DB_FAILURE_FLAGKS_PROCESSINFOGET = 570
DB_FAILURE_FLAGKS_PROCESSINFOSET = 571
DB_FAILURE_FLAGKS_PROCESSINFOVERIFY = 572
DB_FAILURE_UNFLAGKS_PROCESSHANDLE = 573
DB_FAILURE_UNFLAGKS_PROCESSHANDLEINVALID = 574
DB_FAILURE_UNFLAGKS_PROCESSINFOGET = 575
DB_FAILURE_UNFLAGKS_PROCESSINFOSET = 576
DB_FAILURE_UNFLAGKS_PROCESSINFOVERIFY = 577
DB_FAILURE_KSFINDDM2_SHUTDOWNPROGRESS = 578
DB_FAILURE_KSFINDDM2_ENUMKS = 579
DB_FAILURE_KSINIT_SETENV = 580
DB_FAILURE_KSINIT_FLAGKSINJ = 581
DB_FAILURE_KSINIT_CREATETIMER = 582
DB_FAILURE_KSINIT_CREATESIGTHREAD = 583
DB_FAILURE_KSINIT_SETTIMER = 584
DB_FAILURE_KSEXPORTFUNC_CREATEEVENT = 585
DB_FAILURE_KSEXPORTFUNC_WAITSINGLEOBJ = 586
DB_FAILURE_LOGCREATELOGFILE_GETIMAGESIZE = 590
DB_FAILURE_CHECKUUID_LASTCHARNOTVALID = 595
DB_FAILURE_CHECKUUID_FIRSTLENGTH = 596
DB_FAILURE_CHECKUUID_MIDDLEINVALID = 597
DB_FAILURE_ASCIITOWIDE_MUTLIBYTESIZE = 598
DB_FAILURE_ASCIITOWIDE_MUTLIBYTE = 599
DB_FAILURE_WIDETOASCII_MUTLIBYTESIZE = 600
DB_FAILURE_WIDETOASCII_MUTLIBYTE = 601
DB_FAILURE_REGOPENKEY_CREATEKEYHANDLE = 605
DB_FAILURE_REGOPENKEY_CREATEKEYHANDLEINVALID = 606
DB_FAILURE_REGOPENKEY_FINDBUFFSIZE = 607
DB_FAILURE_REGOPENKEY_QUERYINFO = 608
DB_FAILURE_REGGETVALUE_CREATEREGVALUE = 609
DB_FAILURE_REGGETVALUE_ENUMVALUE = 610
DB_FAILURE_REGGETVALUE_GETKEYVALUE = 611
DB_FAILURE_REGGETSUBKEY_CREATEKEYHANDLE = 612
DB_FAILURE_REGGETSUBKEY_ENUMVALUE = 613
DB_FAILURE_REGGETSUBKEY_ENUMKEY = 614
DB_FAILURE_REGGETSUBKEY_OPENREGKEY = 615
DB_FAILURE_REGDELKEY_FAILED = 616
DB_FAILURE_REGCREATEKEY_FAILED = 617
DB_FAILURE_REGSETVALUE_FAILED = 618
DB_FAILURE_REGQUERYVALUE_GETVALUE = 619
DB_FAILURE_REGDELVALUE_FAILED = 620
DB_FAILURE_WRITERSC_PRINTFILENAME = 625
DB_FAILURE_WRITERSC_GETSIZE = 626
DB_FAILURE_WRITERSC_CREATEFILE = 627
DB_FAILURE_RESLIB_FAILURE = 628
DB_FAILURE_RESLIB_UNKNOWN = 629
DB_FAILURE_STUPPART_INVALIDPART = 635
DB_FAILURE_STDEVSYMPATH_GETLOGIVEDRIVE = 636
DB_FAILURE_STDEVSYMPATH_QUERYDOSDEV = 637
DB_FAILURE_STGETBOOTPART_FINDPARTINDEX = 638
DB_FAILURE_STGETBOOTPART_PARSEPARTSTR = 639
DB_FAILURE_STGETBOOTPART_INCOMPAT = 640
DB_FAILURE_STGETCONTPART_UNEXPECTLEN = 641
DB_FAILURE_STGETCONTPART_UNEXPECTPATH = 642
DB_FAILURE_STOPENFILE_CREATEFILE = 643
DB_FAILURE_STGETOBJ_PARSEPATH = 644
DB_FAILURE_STGETOBJ_QUERYINFO = 645
DB_FAILURE_STGENFILENAME_WINDOWSDIR = 646
DB_FAILURE_STGENFILENAME_CONTAINERFAILED = 647
DB_FAILURE_STGENFILENAME_ITERMAX = 648
DB_FAILURE_STINSTALL_STARTARCHIVE = 649
DB_FAILURE_STUNINSTALL_STARTARCHIVE = 650
DB_FAILURE_STEXTRACTVER_MLVER = 651
DB_FAILURE_STEXTRACTVER_DEVTOSYMPATH = 652
DB_FAILURE_STEXTRACTVER_VOLNAME = 653
DB_FAILURE_STISCOMPAT_GLOBALMEMSTATUS = 654
DB_FAILURE_STISCOMPAT_SYSPARTBOOTSEC = 655
DB_FAILURE_STISCOMPAT_SYSPARTCONTSEC = 656
DB_FAILED_TO_WRITE_CONTAINER_FILE_TO_DISK = 657
DB_FAILED_TO_OPEN_CONTAINER_FILE = 658
DB_ST_SEPARATE_BOOT_AND_SYSTEM_PARTITION_BELOW_VISTA = 659
DB_FAILURE_DESTFILEHANDLE_FAILED = 660
DB_FAILURE_DESTREGKEYHANDLE_FAILED = 661
DB_FAILURE_DESTMODINFOLISTHANDLE_FAILED = 662
DB_FAILURE_DESTFILESLISTHANDLE_FAILED = 663
DB_FAILURE_APSSPE_RANDOMIZE = 665
DB_FAILURE_APSSPE_TIMESTAMP = 666
DB_FAILURE_FINDPID_FAILED = 667
DB_FAILURE_FINDPID_SYSINFO = 668
DB_FAILURE_OSVER_FAILED = 669
DB_FAILURE_SUSC_GETTIMESTAMP = 670
DB_FAILURE_SUSC_SETTIMESTAMP = 671
DB_FAILURE_GETIMAGETIMESTAMP_QUERYBASICINFO = 672
DB_FAILED_TO_RESOLVE_ADVAPI32 = 673
DB_FAILED_TO_GPA_SF007 = 674
DB_SF007_FAILED = 675
DB_FAILURE_STGETCONTPART_SYSTEMDIRECTORY = 680
DB_FAILURE_STGETCONTPART_DOSDEVICE = 681
DB_ST_FAILED_TO_PERFORM_BOOT_SECTOR_HASH_VERIFICATION = 682
DB_ST_UNKNOWN_BOOT_SECTOR_FOUND = 683
DB_ST_FAILED_GET_PARAM_RESOURCE_SIZE = 684
DB_ST_FAILED_ALLOCATION_FOR_PARAM_RESOURCE = 685
DB_ST_FAILED_EXTRACT_PARAM_RESOURCE = 686
DB_ST_PREVISTA_POSTVISTA_DUAL_BOOT = 687
DB_ERROR_UNKNOWN_WINERROR = 700
DB_ERROR_UNKNOWN_DW = 701
DB_ERROR_UNKNOWN_KS = 702
DB_ERROR_UNKNOWN_KSUC = 703
DB_ERROR_UNKNOWN_JUVI = 704
DB_ERROR_UNKNOWN_SSCO = 705
DB_ERROR_GEN_FAILURE = 800
DB_ERROR_FILE_NOT_FOUND = 801
DB_ERROR_MR_MID_NOT_FOUND = 802
DB_ERROR_ALREADY_EXISTS = 803
DB_JUVI_ALREADY_PRESENT = 900
DB_JUVI_INIT_KSDATASTORE_LIB = 901
DB_JUVI_OPEN_DATASTORE = 902
DB_JUVI_CREATE_DATASTORE = 903
DB_JUVI_UPGRADE_PERFORMED = 904
DB_JUVI_JUVI_IN_USE = 905
DB_JUVI_PAYLOAD_UNSUPPORTED = 906
DB_JUVI_INVALID_CONFIG = 907
DB_JUVI_INIT_RANDOMIZE = 908
DB_JUVI_EXPAND_ENVIRONMENT_VARIABLES = 909
DB_KSERROR_BASE = 65536
DB_KS_ERROR_DEFAULT = DB_KSERROR_BASE + 2
DB_KS_ERROR_NOT_SUPPORTED = DB_KSERROR_BASE + 3
DB_KS_ERROR_INVALID_PARAMETER = DB_KSERROR_BASE + 4
DB_KS_ERROR_INVALID_DATA = DB_KSERROR_BASE + 5
DB_KS_ERROR_NOT_ENOUGH_MEMORY = DB_KSERROR_BASE + 6
DB_KS_ERROR_EXCEPTION_THROWN = DB_KSERROR_BASE + 7
DB_KS_ERROR_NOT_INITALIZED = DB_KSERROR_BASE + 9
DB_KS_ERROR_SERVICE_NOT_FOUND = DB_KSERROR_BASE + 10
DB_KS_ERROR_EVENT_ERROR = DB_KSERROR_BASE + 11
DB_KS_ERROR_INVALID_PE_FORMAT = DB_KSERROR_BASE + 12
DB_KS_ERROR_RELOCATTING_MODULE = DB_KSERROR_BASE + 13
DB_KS_ERROR_RESOLVE_IMPORTS = DB_KSERROR_BASE + 14
DB_KS_ERROR_OBFUSCATE_PE = DB_KSERROR_BASE + 15
DB_KS_ERROR_DLL_INIT_FAILED = DB_KSERROR_BASE + 16
DB_KS_ERROR_PROCEDURE_NOT_FOUND = DB_KSERROR_BASE + 17
DB_KS_ERROR_INVALID_IMPORT_OF_NON_DLL = DB_KSERROR_BASE + 18
DB_KS_ERROR_FIND_EXPORTED_FUNC = DB_KSERROR_BASE + 19
DB_KS_ERROR_REMOVE_MODULE = DB_KSERROR_BASE + 20
DB_KS_ERROR_MODULE_NOT_FOUND = DB_KSERROR_BASE + 21
DB_KS_ERROR_LOAD_SELF_EXCEPTION = DB_KSERROR_BASE + 22
DB_KS_ERROR_FAILED_CREATETHREAD = DB_KSERROR_BASE + 23
DB_KS_ERROR_UML_IMPORT_OF_ORDINAL = DB_KSERROR_BASE + 24
DB_KS_ERROR_LOADEDCOUNT_MUTEX = DB_KSERROR_BASE + 25
DB_KS_ASBT_RESOURCES_EXHUASTED = DB_KSERROR_BASE + 26
DB_KS_ASBT_WRAPPER_CREATION_FAILED = DB_KSERROR_BASE + 27
DB_KS_ASBT_RESOURCES_EXHAUSTED = DB_KSERROR_BASE + 28
DB_KS_ASBT_VIRTUALALLOC_FAILED = DB_KSERROR_BASE + 29
DB_KS_ERROR_ALREADY_IN_PROCESS = DB_KSERROR_BASE + 30
DB_KS_ERROR_MODULE_TOO_LARGE = DB_KSERROR_BASE + 31
DB_KS_ASBT_TLSALLOC_FAILED = DB_KSERROR_BASE + 32
DB_KS_EXCEPTION_LOADING_DLL = DB_KSERROR_BASE + 33
DB_KS_ERROR_WRITE_FAILED = DB_KSERROR_BASE + 34
DB_KS_ERROR_READ_FAILED = DB_KSERROR_BASE + 35
DB_KS_ERROR_GEN_FAILURE = DB_KSERROR_BASE + 36
DB_KS_ERROR_FILE_NOT_FOUND = DB_KSERROR_BASE + 37
DB_KS_ERROR_MAX_CRASH_COUNT = DB_KSERROR_BASE + 38
DB_KS_ERROR_MR_MID_NOT_FOUND = DB_KSERROR_BASE + 39
DB_KS_ERROR_ALREADY_EXISTS = DB_KSERROR_BASE + 40
DB_KS_ERROR_NO_SYSTEM_RESOURCES = DB_KSERROR_BASE + 41
DB_CUSTOM_ERROR_BASE = 536870912
errorStrings = {DB_SUCCESS: 'Successful return code',
   DB_FAILURE: 'Deprecated: This is a generic error case',
   DB_LOGGER_INIT_FAILED: 'Failed to initialize the SPSP logger',
   DB_COULD_NOT_INTIALIZE_API: 'Failed to initialize the DIBA API',
   DB_INVALID_PARAMETER: 'An invalid parameter was passed to the function.',
   DB_LOGGER_SHUTDOWN_FAILED: 'Failed to shut the logger down.',
   DB_ERROR_KS_COMMUNICATIONS: 'Failed to communicate with KISU',
   DB_ARCHIVE_FAILED: 'Deprecated: Failed to archive a file',
   DB_INSUFFICIENT_MEMORY: 'Failed to allocate memory',
   DB_INSUFFICIENT_BUFFER: 'A buffer passed to a function is not large enough to return the requested data',
   DB_NO_ENTRIES: 'There are no entries, or no further entries in a structure',
   DB_CLEANUP_NATIVEAPI_FAILED: 'Failure to Cleanup NativeAPI',
   DB_ABANDON_ARCHIVE_FAILED: 'Deprecated: Failure to Abandon Archive',
   DB_ABANDON_ARCHIVE_LOGGER_SHUTDOWN_FAILED: 'Deprecated: Failure to Abandon Archive and shutdown logging',
   DB_ABANDON_ARCHIVE_CLEANUP_NATIVE_API_FAILED: 'Deprecated: Failure to Abandon Archive and cleanup Native API',
   DB_CLEANUP_NATIVE_API_LOGGER_SHUTDOWN_FAILED: 'Failure to Cleanup Native API and shutdown logging',
   DB_ABANDON_ARCHIVE_CLEANUP_NATIVE_API_LOGGER_SHUTDOWN_FAILED: 'Deprecated: Failure to Abandon Archive, cleanup Native API, and shutdown logging',
   DB_FILE_ALREADY_EXISTS: 'A file already exists',
   DB_TIMEOUT: 'A timed call timed out before the requested action finished.',
   DB_ABANDONED: 'The action requested was abandoned',
   DB_NO_DRIVER_REGISTRY_KEYS: 'Registry keys were not present to uninstall a driver',
   DB_VALUE_NOT_FOUND: 'The registry value was not found',
   DB_ACCESS_DENIED: 'Access was denied.',
   DB_INCOMPATIBLE_VERSION: 'The requested operation can not be performed due to a version incompatibility.',
   DB_RESOURCE_NOT_FOUND: 'The requested resource cannot be found.',
   DB_KS_COMMS_ALREADY_INITIALIZED: 'Communications with a KISU instance are already initialized',
   DB_KS_INSTANCE_ALREADY_EXISTS: 'An attempt was made to install an instance with the same KISU identifier as an already existing instance.',
   DB_WINDOWS_DEFENDER_RESTORE_ERROR: 'An error occurred while restoring the Real-Time Protection state for Windows Defender which we had already modified to facilitate driver installation.',
   DB_REGISTRY_IO_FAILED: 'The NT error code STATUS_REGISTRY_IO_FAILED was returned while performing an operation.',
   DB_NAME_NOT_FOUND: 'DIBA was unable to find the object specified by the name provided.',
   DB_KS_INIT_FAILED: "Failed to initialize DIBA's KISU signaling.",
   DB_DWBH_INIT_FAILED: 'Failed to initialize BH within DSWI',
   DB_ST_OS_NOT_SUPPORTED: 'OS not supported by SOTI',
   DB_ML_THUNK_DECRYPTION_FAILED: 'Failed to decrypt the MultiLauncher thunk database',
   DB_ML_THUNK_DATABASE_NOT_EMPTY: 'Failed to remove MultiLauncher thunk database. Database not empty',
   DB_ST_FILESYSTEM_NOT_SUPPORTED: 'SOTI does not support this file system',
   DB_ST_MULTIBOOT: 'SOTI Multiboot error - Unused',
   DB_ST_EFI_NOT_SUPPORTED: 'This is an EFI system and SOTI does not support EFI',
   DB_ST_PACK_CONTAINER_FAILED: 'Failed to pack SOTI container file',
   DB_ST_UNPACK_CONTAINER_FAILED: 'Failed to unpack SOTI container file',
   DB_ST_ALREADY_PRESENT: 'An existing SOTI install was already found',
   DB_ML_THUNK_ALREADY_PRESENT: 'Attempt to add a launcher thunk that is already in the multilauncher database',
   DB_ST_EXTRACT_PACK_FAILED: 'Attempt to extract contents of SOTI pack file failed',
   DB_ST_CANT_GET_VERSION: 'Attempt to read version information for existing install failed',
   DB_ST_NEWER_VERSION_PRESENT: "A version of SOTI that is newer that the one you're attempting to install is already present. No installation will be performed.",
   DB_KS_CACHE_ENTRY_INVALID: 'DIBA attempted to call a UML function associated with a KISU instance that is no longer present on the system.',
   DB_MLSTORE_UNSUPPORTED_VERSION: "The version of the module store found on disk isn't supported",
   DB_ST_UPGRADE_PERFORMED: 'An older version of SOTI was found on disk and was upgraded',
   DB_ST_SOTI_IN_USE: 'There is one or more modules in the Multilauncher module store or one or more KISU still relying on SOTI.',
   DB_ST_BITLOCKER_PRESENT: 'BitLocker was detected on the boot partition (SOTI container partition).  This is not supported by SOTI.',
   DB_ST_FAILED_TO_OBTAIN_BITLOCKER_API: 'Unable to obtain FveGetStatusW api from fveapi.dll. This is probably a pre-Vista system.',
   DB_ST_BITLOCKER_API_CALL_FAILED: 'The call to FveGetStatusW in fveapi.dll failed.',
   DB_DRIVER_SIGNING_POLICY_BLOCKS_UNSIGNED: 'An attempt to install KISU using the Launcher service on pre-vista x64 was aborted because DIBA detected the system driver signing policy was set to block.',
   DB_INCOMPATIBLE_PERSISTENCE_MECHANISM: 'An attempt was made to install KISU with a persistence vector not compatible with this system',
   DB_LAUNCHER_DRIVER_NOT_SUPPORTED_ON_64_VISTA: 'Installing KISU with the launcher service is not supported on x64 Vista and beyond due to forced driver signing policies.',
   DB_ST_INSUFFICIENT_MEMORY: 'Installing SOTI on a system with less that 64MB of memory is not supported.',
   DB_ST_UNPACK_CONTAINER_VALIDATION_1_FAILED: 'A validation check performed after unpacking an existing SOTI container file from disk failed.',
   DB_ST_UNPACK_CONTAINER_VALIDATION_2_FAILED: 'A validation check performed after unpacking an existing SOTI container file from disk failed.',
   DB_FAILED_TO_INIT_SYNCHRONIZATION_LOCK: 'Failed to initialize the DIBA synchronization lock',
   DB_TIMEOUT_WAITING_SYNCHRONIZATION_LOCK: 'Timed out waiting for the DIBA synchronization lock',
   DB_FAILED_TO_ARCHIVE_EXISTING_SOTI_BEFORE_UNINSTALL: 'Deprecated: Failed to archive an existing SOTI installation prior to uninstalling',
   DB_FAILED_TO_ARCHIVE_EXISTING_SOTI_BEFORE_UPGRADE: 'Deprecated: Failed to archive an existing SOTI installation prior to upgrading',
   DB_FAILED_TO_UNINSTALL_SOTI_AFTER_FAILED_ARCHIVE: 'Depreacted: Failed to uninstall new SOTI after install/upgrade and failed archive',
   DB_FAILED_TO_ARCHIVE_EXISTING_KISU_BEFORE_UNINSTALL: 'Deprecated: Failed to archive existing KISU prior to uninstall',
   DB_KISU_UNINSTALL_FAILED: "The call to KISU's Uninstall routine failed",
   DB_FAILED_TO_EXTRACT_DW_DRIVER: 'Failed to extract the DSWI driver from the running DIBA installer executable',
   DB_FAILED_TO_INIT_NATIVE_REGISTRY: 'Failed to initialize the native registry wrapper class',
   DB_FAILED_TO_EXTRACT_KISU_RESOURCES: 'Failed to extract SOTI/Multilauncher resources during a KISU install',
   DB_KS_INSTALL_FAILED_TO_EXPAND_ENVIRONMENT_STRING: 'Install failed when attempting to expand environmental strings associated with install path data.',
   DB_KS_INSTALL_FAILED_TO_CONSTRUCT_STRINGS: 'Install failed when attempting to format string data needed during install.',
   DB_KS_INSTALL_FAILED_TO_WRITE_KSDRIVER_TO_REGISTRY: 'Install failed when attempting to write Ksdriver to the registry',
   DB_KS_INSTALL_FAILED_TO_WRITE_UML_TO_REGISTRY: 'Install failed when attempting to write Ksdriver to the registry',
   DB_KS_INSTALL_FAILED_TO_EDIT_LAUNCHER_THUNK_DATA: 'Install failed when attempting to edit the launcher thunk data',
   DB_KS_INSTALL_FAILED_TO_REKEY_LAUNCHER_THUNK_DATA: 'Install failed when attempting to re-key the launcher thunk',
   DB_KS_INSTALL_FAILED_TO_INSTALL_WITH_SUSC: 'Install failed when attempting to install the launcher driver using SUSC',
   DB_KS_INSTALL_FAILED_TO_CREATE_LAUNCHER_THUNK_SUBKEY: 'Install failed when attempting to create the launcher driver subkey in the registry',
   DB_KS_INSTALL_FAILED_TO_WRITE_LAUNCHER_THUNK_VALUE: 'Install failed when attempting to write the launcher thunk to the registry',
   DB_KS_INSTALL_FAILED_TO_SET_SYSTEM_ROOT_VALUE: 'Install failed when attempting to write the system root value to the registry',
   DB_KS_INSTALL_FAILED_TO_CREATE_PROGRESS_SEMAPHORE: 'Install failed when attempting to create the KISU progress semaphore.',
   DB_KS_INSTALL_FAILED_TO_START_LAUNCHER_DRIVER: 'Install failed when attempting to start the KISU launcher driver',
   DB_KS_INSTALL_FAILED_TO_WRITE_KS_PERSISTENCE_ID: 'Install failed when attempting to write the KISU persistence ID to the module store',
   DB_KS_INSTALL_FAILED_TO_WRITE_BH: 'Install failed when attempting to write the BH driver to the KISU module store',
   DB_KS_INSTALL_FAILED_TO_START_BH: 'Install failed when attempting to start the BH driver using KISU',
   DB_KS_INSTALL_FAILED_TO_ARCHIVE_NEW_INSTALL: 'Deprecated: Install failed when attempting to archive the newly installed KISU instance',
   DB_KS_INSTALL_FAILED_TO_CREATE_UML_TEMP_REG_KEY_NAME: 'Install failed to generate a temporary registry key used to store the UML during install of KISU.',
   DB_KS_INSTALL_FAILED_TO_RETRIEVE_LAUNCHER_THUNK: 'Install failed to retrieve launcher thunk data from the registry',
   DB_KS_INSTALL_FAILED_TO_LOAD_KSDRIVER_VIA_DW: 'Install failed to load the KISU driver using DSWI',
   DB_KS_INSTALL_FAILED_TO_UNMUNGE_KS_DRIVER: 'Install failed to unmunge Ksdriver after reading it from the registry',
   DB_KS_INSTALL_FAILED_TO_UNCOMPRESS_KS_DRIVER: 'Install failed to uncompress Ksdriver after reading it from the registry',
   DB_KS_INSTALL_FAILED_TO_FIND_SERVICE_KEYS: 'Install failed to find a sufficient number of registry keys for use when installing KISU.',
   DB_KS_INSTALL_FAILED_TO_ARCHIVE_EXISTING_MULTILAUNCHER: 'Deprecated: Install failed to archive an existing Multilauncher installation prior to installing KISU.',
   DB_KS_INSTALL_FAILED_TO_ARCHIVE_NEW_MULTILAUNCHER: 'Deprecated: Install failed to archive a new Multilauncher installation during KISU installation.',
   DB_KS_INSTALL_FAILED_TO_CREATE_PARAMETERS_SUBKEY: 'Install failed to create a parameters subkey under a KISU selected registry install location.',
   DB_KS_INSTALL_FAILED_TO_CREATE_LOGFILE_FOR_UML: 'Install failed to create a  DIDE log file on disk for use with the KISU UML.',
   DB_KS_INSTALL_FAILED_TO_CREATE_LOGFILE_FOR_KSDRIVER: 'Install failed to create a DIDE log file on disk for use with KsDriver.',
   DB_KS_INSTALL_FAILED_TO_FIND_KEYS_IN_USE_BY_KISU: 'Install failed to generate a list of service keys believed to be in used by other KISU instances',
   DB_KS_INSTALL_FAILED_TO_START_TRANSACTION: 'Install failed to generate a list of service keys believed to be in used by other KISU instances',
   DB_FAILED_TO_ARCHIVE_NEW_SOTI_AFTER_INSTALL: 'Deprecated: Failed to archive new SOTI installation after installation or upgrade',
   DB_INIT_FAILED_TO_DETERMINE_IMAGE_BASE: 'DB_Initialize failed to determine base address of installer image using VirtualQuery',
   DB_GETPERPROCESSUNIQUEGUID_QUERY_BOOT_TIME_FAILED: 'Failed to query system boot time while generating a per system unique guid',
   DB_GETPERPROCESSUNIQUEGUID_STRING_FORMAT_ERROR: 'Failed to format string while generating a per system unique guid',
   DB_GETPERPROCESSUNIQUEGUID_INVALID_PARAMETER: 'Invalid parameter was passed to DB_GetPerProcessUniqueGuid',
   DB_FAILED_TO_APPEND_TO_SYNCHRONIZATION_LOCK_GUID: 'AcquireDBSerializationLock failed to append the Global\\ prefix to the synchronization lock name',
   DB_LOGGINGINIT_PATH_ALLOCATION_ERROR: 'Db_LoggingInit failed to allocate memory to hold logging file path',
   DB_FAILED_TO_INIT_DIDE_CONFIG: 'Db_LoggingCreateLogFile failed to initialize DIDE config interface',
   DB_FAILED_TO_ALLOCATE_MEMORY_FOR_DW_DRIVER: 'DB_NativeInit failed to allocate memory for the packed DSWI driver resource',
   DB_FAILED_TO_EXPAND_ENV_STRING_IN_LOG_PATH: 'DB_LoggingCreateLogPath failed to expand environment strings in the supplied log path name',
   DB_FAILED_TO_CREATE_LOGFILE_DIRECTORY: 'DB_LoggingCreateLogPath failed to create log directory',
   DB_FAILED_TO_SET_LOG_LEVEL: 'DB_LoggingCreateLogFile failed to set logging level',
   DB_FAILED_TO_START_DIDE: 'DB_LoggingInit failed to set logging level',
   DB_SYNCHRONIZATION_OBJECT_ABANDONED: "DIBA found it's global synchronization mutex to be in an abandoned state",
   DB_SYNCHRONIZATION_OBJECT_WAIT_FAILED: 'The call to WaitForSingleObject on the global synchronization mutex failed due to an OS error.',
   DB_FAILED_TO_RELEASE_SYNCHRONIZATION_LOCK: 'The call to ReleaseMtuex on the global synchronization mutex failed due to an OS error.',
   DB_LOGGING_GET_IMAGE_SIZE_FAILED: 'The call to DB_LoggingGetImageSize failed.',
   DB_LOGGING_FAILED_TO_RETRIEVE_FILENAME_SALT: 'The call to DdCfg_RetrieveFilenameOfSaltEx failed',
   DB_LOGGING_FAILED_TO_INIT_LOGWRITER: 'The call to DdLogWriter_Init failed',
   DB_LOGGINGGETOVERRIDESFORIMAGE_INVALID_PARAM: 'An invalid parameter was supplied to DB_LoggingGetOverridesForImage',
   DB_KISU_PROGRESS_SEMAPHORE_NAME_COLLISION: 'When attempting to generate the semaphore name used for the KISU progress semaphore, DIBA detected an existing semaphore with the same name already exists',
   DB_FAILURE_GET_RESOURCE_INSUFFICIENT_MEMORY: 'When attempting to extract resources from the installer binary a memory allocation error occurred.',
   DB_FAILURE_GET_RESOURCE_INVALID_PARAMETER: 'An invalid parameter was supplied to Res_GetResourceEx',
   DB_FAILURE_GET_RESOURCE_FROM_NON_32BIT_BINARY: 'An attempt was made to extract a resource from a non-32-bit binary',
   DB_FAILURE_GET_RESOURCE_FROM_NON_64BIT_BINARY: 'An attempt was made to extract a resource from a non-64-bit binary',
   DB_FAILURE_GET_RESOURCE_INVALID_PE: "During resource extraction the installer's PE header was discovered to be invalid",
   DB_FAILURE_GET_RESOURCE_SECTION_NOT_FOUND: 'During resource extraction ResLib was unable to find the resource section of the installer',
   DB_FAILURE_GET_RESOURCE_PROP_DIR_NOT_FOUND: 'During resource extraction ResLib was unable to find the proprietary resource directory in the installer binary.',
   DB_FAILURE_GET_RESOURCE_CANT_LOAD: 'During resource extraction ResLib encountered a failure calling Win32 LoadResource()',
   DB_FAILURE_GET_RESOURCE_CANT_GET_SIZE: 'During resource extraction ResLib encountered a failure calling Win32 SizeOfResource()',
   DB_FAILURE_GET_RESOURCE_CANT_LOCK: 'During resource extraction ResLib encountered a failure calling LockResource()',
   DB_FAILURE_GET_RESOURCE_CANT_DECOMPRESS: 'While attempting to decompress extracted content, ResLib encountered an error.',
   DB_EXISTING_MODULE_STORE_FOUND_WHEN_INSTALLING_KISU: "During a KISU install using the gen 2 module store, an existing module store for this KISU instance was found, but we couldn't talk to the KISU itself. This likely means there is a defunct KISU instance on the machine.",
   DB_KS_FAILED_TO_INIT_KSDATASTORE_LIB: 'Failed to initialize the KISU DataStore library',
   DB_KS_FAILED_TO_OPEN_DATASTORE: 'Failed to open an existing module store using the KISU DataStore library',
   DB_KS_MODULE_STORE_NOT_FOUND: 'Failed to find an existing module store for the specified KISU instance',
   DB_KS_FAILED_TO_DESTROY_MODULE_STORE: 'Failed to destroy an existing module store using the KISU DataStore library',
   DB_KS_FAILED_INIT_USER_COMMS: 'Failed to initialize the KISU User Comms library',
   DB_KS_FAILED_INIT_NATIVE_API: 'Failed to initialize native api for the KISU User Comms library',
   DB_KS_USERCOMMS_UNKNOWN_OJECT_VERSION: 'Unknown object version',
   DB_JUVI_OS_NOT_SUPPORTED: 'OS not supported by JUVI',
   DB_LAUNCHER_DRIVER_NOT_SUPPORTED_ON_NON64_WIN8: 'Launcher Driver not supported on Win8 non-AMD64',
   DB_ST_FAILED_UPGRADE_FAILED_ROLLBACK: 'An attempt to upgrade an older SOTI failed and we subsequently failed to rollback to the previous existing version.',
   DB_ST_FAILED_UPGRADE_ROLLEDBACK: 'Any attempt to upgrade an older SOTI failed, but we successfully reinstalled the previous version.',
   DB_FAILURE_SECUREFILEDELETION_REOPENINGFILE_DELETEONCLOSE: 'SecureFileDeletion - Failed reopening file for delete on close',
   DB_FAILURE_SECUREFILEDELETION_REOPENINGFILE_OVERWRITE_TRUNCATE: 'SecureFileDeletion - Failed reopening file overwrite truncate existing',
   DB_FAILURE_SECUREFILEDELETION_COMPLETE_OVERWRITE_FILE: 'SecureFileDeletion - Failed complete overwrite of file',
   DB_FAILURE_SECUREFILEDELETION_GETTING_LOWORDER_FILESIZE: 'SecureFileDeletion - Failed getting low order file size',
   DB_FAILURE_SECUREFILEDELETION_GET_FILE_SIZE: 'SecureFileDeletion - Failed to get file size',
   DB_FAILURE_SECUREFILEDELETION_GET_FILE_HANDLE: 'SecureFileDeletion - Failed to get file handle',
   DB_FAILURE_ABANDONARCHIVE_FLUSH: 'DB_AbandonArchive - Failed to flush archive',
   DB_FAILURE_ROLLBACKARCHIVE_RESTORE: 'DB_RollbackArchive - Failed to restore archive',
   DB_FAILURE_DEBUGMEMCHECKFORLEAKS_FOUNDLEAK: 'DB_DebugMemCheckForLeaks - Memory leaks have been detected',
   DB_FAILURE_LOADDRIVER_LOAD: 'DB_LoadDriver - Failed to load driver',
   DB_FAILURE_LOADDRIVER_ALREADYLOADED: 'DB_LoadDriver - Driver already loaded',
   DB_FAILURE_LOADDRIVER_UNLOAD: 'DB_LoadDriver - Failed to unload driver',
   DB_FAILURE_UNLOADDRIVER_UNLOAD: 'DB_UnloadDriver - Failed to unload driver',
   DB_FAILURE_UNLOADDRIVER_LOAD: 'DB_UnloadDriver - Failed to load driver',
   DB_FAILURE_STARTDRIVER_WITHSERVICENAME_PRINT_SERIVCEPATH: 'DB_StartDriverWithServiceName - Failed to print service path',
   DB_FAILURE_STOPDRIVER_WITHSERVICENAME_PRINT_SERVICEPATH: 'DB_StopDriverWithServiceName - Failed to print service path',
   DB_FAILURE_DISABLEWINDOWSDEFENDERRTP_QUERYREGISTRY: 'DisableWindowsDefenderRTP - Failed to query registry',
   DB_FAILURE_INSTALLDRIVER_DISABLEWINDOWSDEFENDER: 'DB_InstallDriver - Failed to disable Windows Defender',
   DB_FAILURE_INSTALLDRIVER_INSTALLFAILED: 'DB_InstallDriver - Failed to install driver',
   DB_FAILURE_INSTALLDRIVER_INSTALLFAILED_REGISTRY_ENTRY: 'DB_InstallDriver - Failed to install driver due to a registry entry. ERROR_INSTALL_FAILED_REGISTRY_ENTRY',
   DB_FAILURE_INSTALLDRIVER_INSTALLFAILED_DROP_FILE: 'DB_InstallDriver - Failed to install driver due to drop file. ERROR_INSTALL_FAILED_DROP_FILE',
   DB_FAILURE_INSTALLDRIVER_INSTALLFAILED_CANT_START: "DB_InstallDriver - Failed to install driver due to can't start. ERROR_INSTALL_CANT_START",
   DB_FAILURE_CONVERTPETIMETOFILETIME_SYSTEMTIME: 'ConvertPeTimeToFileTime - Failed to convert system time to file time',
   DB_FAILURE_GETIMAGETIMESTAMP_OPENFILE: 'GetImageTimestamp - Failed to open file',
   DB_FAILURE_GETIMAGETIMESTAMP_FILEHANDLE: 'GetImageTimestamp - Failed to get file handle',
   DB_FAILURE_GETIMAGETIMESTAMP_MAPSECTION: 'GetImageTimestamp - Failed to map section',
   DB_FAILURE_GETIMAGETIMESTAMP_MAP_INVALIDHANDLE: 'GetImageTimestamp - Invalid handle for map section',
   DB_FAILURE_GETIMAGETIMESTAMP_GETPROCESS: 'GetImageTimestamp - Failed to get process handle',
   DB_FAILURE_GETIMAGETIMESTAMP_PROCESS_INVALID: 'GetImageTimestamp - Process handle is invalid',
   DB_FAILURE_GETIMAGETIMESTAMP_MAPVIEWOFSECTION: 'GetImageTimestamp - Failed to map view of section',
   DB_FAILURE_GETIMAGETIMESTAMP_MAPVIEW_INVALID: 'GetImageTimestamp - Mapping is invalid',
   DB_FAILURE_GETIMAGETIMESTAMP_TIMESTAMPGET: 'GetImageTimestamp - Failed to get timestamp from file',
   DB_FAILURE_INSTALLDRIVERWITH_SUSC_IMAGETIMESTAMP_GET: 'DB_InstallDriverWithSuSc - Failed to get image timestamp',
   DB_FAILURE_INSTALLDRIVERWITH_SUSC_IMAGETIMESTAMP_SET: 'DB_InstallDriverWithSuSc - Failed to set image timestamp',
   DB_FAILURE_INSTALLDRIVERWITH_SUSC_FILEINFO_SAMPLE_GET: 'DB_InstallDriverWithSuSc - Failed to retrieve file info from sample driver.',
   DB_FAILURE_INSTALLDRIVERFROM_RESOURCEDEF_RESOURCESIZE_GET: 'DB_InstallDriverFromResourceWithDefaults - Failed to get resource size',
   DB_FAILURE_INSTALLDRIVERFROM_RESOURCEDEF_PRINT_DRIVERNAME: 'DB_InstallDriverFromResourceWithDefaults - Failed to print driver file name',
   DB_FAILURE_INSTALLDRIVERFROM_RESOURCEDEF_INSTALLDRIVER: 'DB_InstallDriverFromResourceWithDefaults - Failed to install driver',
   DB_FAILURE_UNINSTALLDRIVER_PRINT_REGPATH: 'DB_UninstallDriver - Failed to print reg path',
   DB_FAILURE_UNINSTALLDRIVER_REG_VALUE_GET: 'DB_UninstallDriver - Failed to get value from reg',
   DB_FAILURE_UNINSTALLDRIVER_UNINSTALL: 'DB_UninstallDriver - Uninstall failed with unknown error',
   DB_FAILURE_UNINSTALLDRIVER_UNINSTALL_REGISTRY_ENTRY: 'DB_UninstallDriver - Uninstall failed due to registry entry',
   DB_FAILURE_UNINSTALLDRIVER_UNINSTALL_CANTERASEFILE: "DB_UninstallDriver - Uninstall failed because it can't erase file",
   DB_FAILURE_UNINSTALLDRIVER_UNINSTALL_CANTSTOP: "DB_UninstallDriver - Uninstall failed because it can't stop",
   DB_FAILURE_UNINSTALLDRIVER_UNINSTALL: 'DB_UninstallDriver - Uninstall failed with unknown error',
   DB_FAILURE_OPENEVENT_CREATE_EVENTHANDLE: 'DB_OpenEvent - Failed to create event handle',
   DB_FAILURE_OPENEVENT_ZWOPEN_UNKNOWN: 'DB_OpenEvent - An unknown error was returned from DB_NativeZwOpenEvent',
   DB_FAILURE_SETEVENT_ZWSET_UNKNOWN: 'DB_SetEvent - An unknown error was returned from\tDB_NativeZwSetEvent',
   DB_FAILURE_RESETEVENT_ZWRESET_UNKNOWN: 'DB_ResetEvent - An unknown error was returned from DB_NativeZwResetEvent',
   DB_FAILURE_WAITFORSINGLEOBJECT_UNKNOWN: 'DB_WaitForSingleObject - An unknown error was returned from DwZwWaitForSingleObject',
   DB_FAILURE_CREATEEVENT_CREATEHANDLE: 'DB_CreateEvent - Failed to create event handle',
   DB_FAILURE_CREATEEVENT_INIT_SECURITY_DESC: 'DB_CreateEvent - Failed in InitializeSecurityDescriptor',
   DB_FAILURE_CREATEEVENT_SET_SECURITY_DESC_DACL: 'DB_CreateEvent - Failed in SetSecurityDescriptorDacl',
   DB_FAILURE_CREATEEVENT_SET_SECURITY_OBJECT: 'DB_CreateEvent - Failed in DB_SetSecurityObject',
   DB_FAILURE_CREATEEVENT_FAILED: 'DB_CreateEvent - Failed to create an event',
   DB_FAILURE_SIMPLECREATE_CREATEFILEHANDLE: 'DB_SimpleCreateFileEx - Failed to create file handle',
   DB_FAILURE_SIMPLECREATE_FAILED: 'DB_SimpleCreateFileEx - Native SimpleCreateFileW failed',
   DB_FAILURE_GETFILESIZE_FAILED: 'DB_GetFileSize - Native GetFileSize failed',
   DB_FAILURE_SETSECURITYOBJ_FAILED: 'DB_SetSecurityObject - Native ZwSetSecurityObject failed',
   DB_FAILURE_RENAMEFILE_FAILED: 'DB_RenameFile - Native RenameFile failed',
   DB_FAILURE_WRITEFILE_FAILED: 'DB_WriteFile - Native ZwWriteFile failed',
   DB_FAILURE_READFILE_FAILED: 'DB_ReadFile - Native ZwReadFile failed',
   DB_FAILURE_FINDFILES_SNWPRINTF: 'DB_FindFiles - Failed to print path',
   DB_FAILURE_FINDFILES_CREATEDIRHANDLE: 'DB_FindFiles - Failed to create directory handle',
   DB_FAILURE_FINDFILES_CREATEFILELISTHANDLE: 'DB_FindFiles - Failed to create file list handle',
   DB_FAILURE_FINDFILES_QUERYDIR: 'DB_FindFiles - Failed to query directory',
   DB_FAILURE_FINDFILES_FINDFILE: 'DB_FindFiles - Failed to find file',
   DB_FAILURE_FINDFILES_UNEXPECTED: 'DB_FindFiles - Unexpected error',
   DB_FAILURE_GETNEXTFILE_DATANULL: 'DB_GetNextFile - Next file data is NULL',
   DB_FAILURE_DRIVELETTER_OBJECTNAMEINFO: 'DB_GetDriveLetterByHandle - Failed to get object name information',
   DB_FAILURE_DRIVELETTER_OPENDIROBJ: 'DB_GetDriveLetterByHandle - Failed to open directory object',
   DB_FAILURE_DRIVELETTER_OPENSYMLINK: 'DB_GetDriveLetterByHandle - Failed to object symbolic link object',
   DB_FAILURE_DRIVELETTER_FINDLOGICDRIVES: 'DB_GetDriveLetterByHandle - Failed to find logic drives',
   DB_FAILURE_GETFILEINFO_GETFILEBASICINFO: 'DB_GetFileInformation - Failed to get file basic information',
   DB_FAILURE_GETFILEINFO_GETFILESTANDARDINFO: 'DB_GetFileInformation - Failed to get file standard information',
   DB_FAILURE_GETFILEINFO_GETFILENAMEINFO: 'DB_GetFileInformation - Failed to get file standard information',
   DB_FAILURE_SETFILEINFO_SETFILEENDINFO: 'DB_SetFileInformation - Failed to set file end information',
   DB_FAILURE_SETFILEINFO_SETFILEBASICINFO: 'DB_SetFileInformation - Failed to set file basic information',
   DB_FAILURE_FILECLOSE_FAILURE: 'DB_Close - Failed to destroy file handle',
   DB_FAILURE_CRTFILEMAPPING_CREATEMAPHANDLE: 'DB_SimpleCreateFileMapping - Failed to create map handle',
   DB_FAILURE_CRTFILEMAPPING_INITSECURITYDESC: 'DB_SimpleCreateFileMapping - Failed to initialize security descriptor',
   DB_FAILURE_CRTFILEMAPPING_SETSECURITYDESCDACL: 'DB_SimpleCreateFileMapping - Failed to set security descriptor DACL',
   DB_FAILURE_CRTFILEMAPPING_SETSECURITYOBJ: 'DB_SimpleCreateFileMapping - Failed to set security object',
   DB_FAILURE_MAPVIEWFILE_OPENPROCESS: 'DB_MapViewOfFile - Failed to open process',
   DB_FAILURE_MAPVIEWFILE_MAPVIEWSECTION: 'DB_MapViewOfFile - Failed to map view of section',
   DB_FAILURE_UNMAPVIEWFILE_OPENPROCESS: 'DB_UnmapViewOfFile - Failed to open process',
   DB_FAILURE_UNMAPVIEWFILE_UNMAPVIEWSECTION: 'DB_UnmapViewOfFile - Failed to unmap view of section',
   DB_FAILURE_FILECLOSE_INVALIDTYPE: 'DB_Close - Invalid DB Handle type encountered',
   DB_FAILURE_DELETE_FILE_SECURE_DELETE_FAILED: 'DB_DeleteFile - Failed to secure delete a file',
   DB_FAILURE_UNMAPVIEWFILE_UNMAPVIEWSECTION: 'DB_UnmapViewOfFile - Failed to unmap view of section',
   DB_FAILURE_FILECLOSE_INVALIDTYPE: 'DB_Close - Invalid DB Handle type encountered',
   DB_FAILURE_SELFDEL_MODULEFILENAME: 'DB_SelfDelete - Failed to get module file name',
   DB_FAILURE_SELFDEL_PRINTPREFIX: 'DB_SelfDelete - Failed to print prefixed filename',
   DB_FAILURE_SELFDEL_ASYNC_FILEDELETE: 'DB_SelfDelete - Failed to DW async file deletion',
   DB_FAILURE_CLEANNATVIE_EXCEPT: 'CleanNativeAPI - An exception occured',
   DB_FAILURE_KSINITCOMMS_NOSTATUS: 'DB_KsInitializeCommsEx - Failed to set a status code.',
   DB_FAILURE_KSSHUTDOWN_FAILED: 'DB_KsShutdownComms - Failed to shutdown KISU comms',
   DB_FAILURE_KSWRITECOMPMUNGREGKEY_CREATEKEY: 'DB_KsWriteCompressedAndMungedRegKeyInternal - Failed to create reg key',
   DB_FAILURE_KSWRITECOMPMUNGREGKEY_COMPRESS: 'DB_KsWriteCompressedAndMungedRegKeyInternal - Failed to compress key value',
   DB_FAILURE_KSWRITECOMPMUNGREGKEY_MUNGE: 'DB_KsWriteCompressedAndMungedRegKeyInternal - Failed to munge the compressed key value',
   DB_FAILURE_KSWRITECOMPMUNGREGKEY_SAVEVALUE: 'DB_KsWriteCompressedAndMungedRegKeyInternal - Failed to save value to registry',
   DB_FAILURE_KSWRITECOMPMUNGREGKEY_ALREADYMUNGCOMP: 'DB_KsWriteCompressedAndMungedRegKeyInternal - Failed to save already compressed and munged value to registry',
   DB_FAILURE_FINDMULTIKSSRVKEY_NOELIGIBLE: 'DB_FindMultipleKillsuitServiceKeys - Failed to find an eligible serivice key',
   DB_FAILURE_KSUNINSTALLST_PRINTTHUNKSVCNAME: 'DB_KsUninstallSt - Failed to print lanucher thunk service name',
   DB_FAILURE_KSUNINSTALLST_ARCHIVE: 'DB_KsUninstallSt - Failed to archive multi launcher installation',
   DB_FAILURE_KSDELETEMOD_MODINFOSIZE: 'DB_KsDeleteModuleInternal - Failed to get module info size',
   DB_FAILURE_KSDELETEMOD_READMODINFO: 'DB_KsDeleteModuleInternal - Failed to read module info',
   DB_FAILURE_KSDELETEMOD_MODDATASIZE: 'DB_KsDeleteModuleInternal - Failed to get module data size',
   DB_FAILURE_KSDELETEMOD_READMODDATA: 'DB_KsDeleteModuleInternal - Failed to read module data',
   DB_FAILURE_KSDELETEMOD_ARCHIVEMOD: 'DB_KsDeleteModuleInternal - Failed to archive module',
   DB_FAILURE_KSDELETEMOD_INSUFFICIENT_MEMORY: 'DB_KsDeleteModuleInternal - Failed to archive module',
   DB_FAILURE_KSVERSION_FAILED: 'DB_KsGetVersion - Failed to get KISU Version',
   DB_FAILURE_KSMODULEINFOLIST_LISTOBJECTSSIZE: 'DB_KsGetModuleInfoList - Failed to get KISU list objects size',
   DB_FAILURE_KSMODULEINFOLIST_MODINFOLISTHANDLE: 'DB_KsGetModuleInfoList - Failed to create handle for module info list',
   DB_FAILURE_KSUNINSTALLPERSIST_INVALIDID: 'KsUninstallPersistence - Invalid persistence id',
   DB_FAILURE_KSUNINSTALLINT_START_TRANSAC: 'KsUninstallInternal - Failed to start transaction',
   DB_FAILURE_KSUNINSTALLINT_CACHE_REMOVEKS: 'KsUninstallInternal - Failed to remove KISU instance from cache',
   DB_FAILURE_KSVALMODSTORE_MODSTOREDIRSIZE: 'DB_KsValidateModuleStore - Failed to get module store dir size',
   DB_FAILURE_KSVALMODSTORE_MODSTOREDIR: 'DB_KsValidateModuleStore - Failed to get module store dir',
   DB_FAILURE_KSVALMODSTORE_MODSTOREDIR_DECRYPT: 'DB_KsValidateModuleStore - Failed to decrypt module store dir',
   DB_FAILURE_KSVALMODSTORE_MODSTOREDIRENTRYSIZE: 'DB_KsValidateModuleStore - Failed to get module store dir entry size',
   DB_FAILURE_KSVALMODSTORE_MODSTOREDIRENTRY: 'DB_KsValidateModuleStore - Failed to get module store dir entry',
   DB_FAILURE_KSVALMODSTORE_MODSTOREDIRENTRY_DECRYPT: 'DB_KsValidateModuleStore - Failed to decrypt module store dir entry',
   DB_FAILURE_KSVALMODSTORE_COUNTVALUES: 'DB_KsValidateModuleStore - Failed to count values',
   DB_FAILURE_KSLOADMOD_FAILED: 'KsLoadModuleInternal - Failed to load the module',
   DB_FAILURE_KSLOADMOD_ARCHIVE: 'KsLoadModuleInternal - Failed to archive load the module',
   DB_FAILURE_KSSTARTSTOPDRIVER_ARCHIVE: 'DB_KsStartStopDriverInternal - Failed to archive start/stop of the driver',
   DB_FAILURE_REMOVEKSINSTANCEFROMCACHE: 'RemoveKISUInstanceFromCache - Failed to perform',
   DB_FAILURE_REMOVEKSINSTANCEFROMCACHE_EMPTY: 'RemoveKISUInstanceFromCache - List is empty',
   DB_FAILURE_FREEKSINSTANCEFROMCACHE: 'FreeKISUInstanceCache - Failed to perform',
   DB_FAILURE_KSMODIDS_LISTOBJECTSSIZE: 'GetKsModuleIDsList - Failed to get KS list objects size',
   DB_FAILURE_KSMODIDS_ALLOCATEMEM: 'GetKsModuleIDsList - Failed to allocate memory for KISU list objects',
   DB_FAILURE_KSMODIDS_REALLOCATEMEM: 'GetKsModuleIDsList - Failed to reallocate memory for KISU list objects',
   DB_FAILURE_FINDKSINST_NOTFOUND: 'FindKISUInstanceInCache - Failed to reallocate memory for KISU list objects',
   DB_FAILURE_FINDKSINST_UCGETUMLFUNC: 'FindKISUInstanceInCache - Call to KS_IcGetUMLFunction failed',
   DB_FAILURE_WAITKSINST_WAITSINGLEOBJ_SIGNAL: 'WaitForDBKsInitialization - WaitForSingleObject failed for KISU Signal',
   DB_FAILURE_WAITKSINST_WAITSINGLEOBJ_THREAD: 'WaitForDBKsInitialization - WaitForSingleObject failed for KISU Thread Init',
   DB_FAILURE_WAITKSINST_WAITSINGLEOBJ_EXITCODE: 'WaitForDBKsInitialization - ExitCodeThread failed',
   DB_FAILURE_ENUMKSINST_WAIT: 'KISU_EnumerateInstances - WaitForDBKsInitialization failed',
   DB_FAILURE_CFGDM2_VERCFG: 'KISUQueryInstanceConfigurationDM2 - Failed on KISU',
   DB_FAILURE_CFGDM2_BUFOVERFLOW: 'KISUQueryInstanceConfigurationDM2 - KillSuit with paths that would exceed these fixed buffer size.',
   DB_FAILURE_KSINITCOMMSINT_FIND: 'KISUInitializeCommsInternal - Failed to find KISU in cache',
   DB_FAILURE_KSINITCOMMSINT_CREATEVENT: 'KISUInitializeCommsInternal - Failed to create event',
   DB_FAILURE_KSINITCOMMSINT_SIGNALTHREAD: 'KISUInitializeCommsInternal - Failed to create KISU signaling thread',
   DB_FAILURE_KSCFGINT_POPULATE: 'GetDBKsConfigurationInternal - Failed to populate config',
   DB_FAILURE_FLAGKS_PROCESSHANDLE: 'DB_FlagForKSInjection - Failed to get a process handle',
   DB_FAILURE_FLAGKS_PROCESSHANDLEINVALID: 'DB_FlagForKSInjection - Process handle is invalid',
   DB_FAILURE_FLAGKS_PROCESSINFOGET: 'DB_FlagForKSInjection - Failed to get process info',
   DB_FAILURE_FLAGKS_PROCESSINFOSET: 'DB_FlagForKSInjection - Failed to set process info',
   DB_FAILURE_FLAGKS_PROCESSINFOVERIFY: 'DB_FlagForKSInjection - Failed to verify process info',
   DB_FAILURE_UNFLAGKS_PROCESSHANDLE: 'DB_UnflagForKSInjection - Failed to get process handle',
   DB_FAILURE_UNFLAGKS_PROCESSHANDLEINVALID: 'DB_UnflagForKSInjection - Process handle is invalid',
   DB_FAILURE_UNFLAGKS_PROCESSINFOGET: 'DB_UnflagForKSInjection - Failed to get process info',
   DB_FAILURE_UNFLAGKS_PROCESSINFOSET: 'DB_UnflagForKSInjection - Failed to set process info',
   DB_FAILURE_UNFLAGKS_PROCESSINFOVERIFY: 'DB_UnflagForKSInjection - Failed to verify process info',
   DB_FAILURE_KSFINDDM2_SHUTDOWNPROGRESS: 'DB_KsFindDM2Killsuits - Shutdown in progress',
   DB_FAILURE_KSFINDDM2_ENUMKS: 'DB_KsFindDM2Killsuits - Shutdown in progress',
   DB_FAILURE_KSINIT_SETENV: 'DB_KsInitialize - Failed to set environment variable',
   DB_FAILURE_KSINIT_FLAGKSINJ: 'DB_KsInitialize - Failed to flag for KISU injection',
   DB_FAILURE_KSINIT_CREATETIMER: 'DB_KsInitialize - Failed to create timer',
   DB_FAILURE_KSINIT_CREATESIGTHREAD: 'DB_KsInitialize - Failed to create KISU signaling thread',
   DB_FAILURE_KSINIT_SETTIMER: 'DB_KsInitialize - Failed to set signaling timer',
   DB_FAILURE_KSEXPORTFUNC_CREATEEVENT: 'GetKsNonExportedFunctionPtrs - Failed to create event status',
   DB_FAILURE_KSEXPORTFUNC_WAITSINGLEOBJ: 'GetKsNonExportedFunctionPtrs - Failed to receive signal from module helper dll status',
   DB_FAILURE_LOGCREATELOGFILE_GETIMAGESIZE: 'DB_LoggingCreateLogFileForImage - Failed to get image size',
   DB_FAILURE_CHECKUUID_LASTCHARNOTVALID: 'CheckUUIDW - Failed to get image size',
   DB_FAILURE_CHECKUUID_FIRSTLENGTH: 'CheckUUIDW - Invalid length or first character invalid.',
   DB_FAILURE_CHECKUUID_MIDDLEINVALID: 'CheckUUIDW - Invalid middle character',
   DB_FAILURE_ASCIITOWIDE_MUTLIBYTESIZE: 'DB_MlAsciiToWide - MultiByteToWideChar for size failed',
   DB_FAILURE_ASCIITOWIDE_MUTLIBYTE: 'DB_MlAsciiToWide - MultiByteToWideChar failed',
   DB_FAILURE_WIDETOASCII_MUTLIBYTESIZE: 'DB_MlWideToAscii - MultiByteToWideChar for size failed',
   DB_FAILURE_WIDETOASCII_MUTLIBYTE: 'DB_MlWideToAscii - MultiByteToWideChar failed',
   DB_FAILURE_REGOPENKEY_CREATEKEYHANDLE: 'DB_RegOpenKey - Failed to create reg key handle',
   DB_FAILURE_REGOPENKEY_CREATEKEYHANDLEINVALID: 'DB_RegOpenKey - Failed to open reg key',
   DB_FAILURE_REGOPENKEY_FINDBUFFSIZE: 'DB_RegOpenKey - Failed to find buffer size for key info',
   DB_FAILURE_REGOPENKEY_QUERYINFO: 'DB_RegOpenKey - Failed to query key info',
   DB_FAILURE_REGGETVALUE_CREATEREGVALUE: 'DB_RegGetValue - Failed to create reg value',
   DB_FAILURE_REGGETVALUE_ENUMVALUE: 'DB_RegGetValue - Failed to enumerate value key',
   DB_FAILURE_REGGETVALUE_GETKEYVALUE: 'DB_RegGetValue - Failed to get the key value',
   DB_FAILURE_REGGETSUBKEY_CREATEKEYHANDLE: 'DB_RegGetSubkey - Failed to get key handle',
   DB_FAILURE_REGGETSUBKEY_ENUMVALUE: 'DB_RegGetSubkey - Failed to enumerate value key',
   DB_FAILURE_REGGETSUBKEY_ENUMKEY: 'DB_RegGetSubkey - Failed to enumerate key',
   DB_FAILURE_REGGETSUBKEY_OPENREGKEY: 'DB_RegGetSubkey - Failed to open reg key',
   DB_FAILURE_REGDELKEY_FAILED: 'DB_RegDeleteKey - Failed to delete key',
   DB_FAILURE_REGCREATEKEY_FAILED: 'DB_RegCreateKey - Failed to create key',
   DB_FAILURE_REGSETVALUE_FAILED: 'DB_RegSetValue - Failed to set value',
   DB_FAILURE_REGQUERYVALUE_GETVALUE: 'DB_RegQuerySingleValue - Failed to get value',
   DB_FAILURE_REGDELVALUE_FAILED: 'DB_RegDeleteValue - Failed to delete value',
   DB_FAILURE_WRITERSC_PRINTFILENAME: 'DB_WriteResourceToFile - Failed to copy string into the wide character buffer',
   DB_FAILURE_WRITERSC_GETSIZE: 'DB_WriteResourceToFile - Failed to get resource size',
   DB_FAILURE_WRITERSC_CREATEFILE: 'DB_WriteResourceToFile - Failed to create file',
   DB_FAILURE_RESLIB_FAILURE: 'DB_ResLibToDiBaError - DIBA error representing RES_FAILURE',
   DB_FAILURE_RESLIB_UNKNOWN: 'DB_ResLibToDiBaError - ResLib error',
   DB_FAILURE_STUPPART_INVALIDPART: 'St_UpdatePartitionIndexInBootBuf - Invalid patition',
   DB_FAILURE_STDEVSYMPATH_GETLOGIVEDRIVE: 'St_DeviceToSymbolicPath - GetLogicDriveStringsW failed',
   DB_FAILURE_STDEVSYMPATH_QUERYDOSDEV: 'St_DeviceToSymbolicPath - QueryDosDeviceW failed',
   DB_FAILURE_STGETBOOTPART_FINDPARTINDEX: 'St_GetBootAndCntrPartitionIndex - Failed to find partition index',
   DB_FAILURE_STGETBOOTPART_PARSEPARTSTR: "St_GetBootAndCntrPartitionIndex - Can't parse partition string",
   DB_FAILURE_STGETBOOTPART_INCOMPAT: 'St_GetBootAndCntrPartitionIndex - Partition strings incompatible',
   DB_FAILURE_STGETCONTPART_UNEXPECTLEN: 'St_GetContainerPartition - Unexpected length for partition path',
   DB_FAILURE_STGETCONTPART_UNEXPECTPATH: 'St_GetContainerPartition - System partition has unexpected pathname',
   DB_FAILURE_STOPENFILE_CREATEFILE: 'St_OpenFileById - DwZwCreateFile failed',
   DB_FAILURE_STGETOBJ_PARSEPATH: "St_GetObjectId - Can't parse file path",
   DB_FAILURE_STGETOBJ_QUERYINFO: 'St_GetObjectId - Failed to obtain NTFS object id',
   DB_FAILURE_STGENFILENAME_WINDOWSDIR: 'St_GenerateContainerFileName - GetWindowsDirectoryW failed',
   DB_FAILURE_STGENFILENAME_CONTAINERFAILED: 'St_GenerateContainerFileName - Routine failed',
   DB_FAILURE_STGENFILENAME_ITERMAX: 'St_GenerateContainerFileName - Failed to find model file after 16 attempts',
   DB_FAILURE_STINSTALL_STARTARCHIVE: 'DB_StInstallInternal - Failed to start archive transaction',
   DB_FAILURE_STUNINSTALL_STARTARCHIVE: 'DB_StUninstallInternal - Failed to start archive transaction',
   DB_FAILURE_STEXTRACTVER_MLVER: 'DB_StExtractVersionInformation - Failed to obtain SOTI multilauncher version information',
   DB_FAILURE_STEXTRACTVER_DEVTOSYMPATH: 'DB_StCheckFveStatus - St_DeviceToSymbolicPath failed',
   DB_FAILURE_STEXTRACTVER_VOLNAME: 'DB_StCheckFveStatus - GetVolumeNameForVolumeMountPointW failed',
   DB_FAILURE_STISCOMPAT_GLOBALMEMSTATUS: 'DB_StIsSystemSOTICompatible - GlobalMemoryStatusEx failed',
   DB_FAILURE_STISCOMPAT_SYSPARTBOOTSEC: 'DB_StIsSystemSOTICompatible - Failed to read system partition boot sector',
   DB_FAILURE_STISCOMPAT_SYSPARTCONTSEC: 'DB_StIsSystemSOTICompatible - Failed to read system partition containater sector',
   DB_FAILED_TO_WRITE_CONTAINER_FILE_TO_DISK: 'St_DropContainerFileToDisk - failed to write container file contents to disk',
   DB_FAILED_TO_OPEN_CONTAINER_FILE: 'St_DropContainerFileToDisk - failed to open container file',
   DB_ST_SEPARATE_BOOT_AND_SYSTEM_PARTITION_BELOW_VISTA: 'DB_StIsSystemSOTICompatible - Separate boot and system partitions not supported by SOTI on systems below VISTA.',
   DB_FAILURE_DESTFILEHANDLE_FAILED: 'DB_DestroyFileHandle - Failed to close file handle',
   DB_FAILURE_DESTREGKEYHANDLE_FAILED: 'DB_DestroyRegistryKeyHandle - Failed to close reg key handle',
   DB_FAILURE_DESTMODINFOLISTHANDLE_FAILED: 'DB_DestroyModuleInfoListHandle - Failed to free list',
   DB_FAILURE_DESTFILESLISTHANDLE_FAILED: 'DB_DestroyFilesListHandle - Failed to free list',
   DB_FAILURE_APSSPE_RANDOMIZE: 'DB_ApplySuScToPE - Failed to randomize image time',
   DB_FAILURE_APSSPE_TIMESTAMP: 'DB_ApplySuScToPE - Failed to set timestamp in image',
   DB_FAILURE_FINDPID_FAILED: 'DB_FindPID - Routine failed',
   DB_FAILURE_FINDPID_SYSINFO: 'DB_FindPID - System information failed',
   DB_FAILURE_OSVER_FAILED: 'DB_GetOsVersion - Failed to get os version',
   DB_FAILURE_SUSC_GETTIMESTAMP: 'DB_SuScPeWithTemplate - Failed to GetTimeStamp of file',
   DB_FAILURE_SUSC_SETTIMESTAMP: 'DB_SuScPeWithTemplate - Res_TimestampSet failed',
   DB_FAILURE_GETIMAGETIMESTAMP_QUERYBASICINFO: 'GetImageTimestamp - ZwQueryInformationFile FileBasicInfo failed',
   DB_FAILED_TO_RESOLVE_ADVAPI32: 'DB_PerformMD4Hash - Failed to LoadLibrary advapi32.dll',
   DB_FAILED_TO_GPA_SF007: 'DB_PerformMD4Hash - Failed to GetProcessAddress SystemFunction007',
   DB_SF007_FAILED: 'DB_PerformMD4Hash - Call to SystemFunciton007 failed',
   DB_FAILURE_STGETCONTPART_SYSTEMDIRECTORY: 'St_GetContainerPartition - Failed to get the system directory',
   DB_FAILURE_STGETCONTPART_DOSDEVICE: 'St_GetContainerPartition - Failed to query the DOS device',
   DB_ST_FAILED_TO_PERFORM_BOOT_SECTOR_HASH_VERIFICATION: 'DB_StIsSystemSOTICompatible - Failed to check boot sector hash against known goods',
   DB_ST_UNKNOWN_BOOT_SECTOR_FOUND: 'DB_StIsSystemSOTICompatible - A boot sector not on the known good hash list was found',
   DB_ST_FAILED_GET_PARAM_RESOURCE_SIZE: 'DB_StInitSOTIInstallLib - Failed to determine packed param data resource size',
   DB_ST_FAILED_ALLOCATION_FOR_PARAM_RESOURCE: 'DB_StInitSOTIInstallLib - Failed to allocate memory for packed param data',
   DB_ST_FAILED_EXTRACT_PARAM_RESOURCE: 'DB_StInitSOTIInstallLib - Failed to extract packed param data',
   DB_ST_PREVISTA_POSTVISTA_DUAL_BOOT: 'DB_StInitSOTIInstallLib - Possible dual boot system -- unsupported',
   DB_ERROR_UNKNOWN_WINERROR: 'Failed to convert an internal error to DB Error namespace',
   DB_ERROR_UNKNOWN_DW: 'An unknown DW Error was encountered',
   DB_ERROR_UNKNOWN_KS: 'An unknown KISU Error was encountered',
   DB_ERROR_UNKNOWN_KSUC: 'An unknown KISU UserComms Error was encountered',
   DB_ERROR_UNKNOWN_JUVI: 'An unknown JUVI Error was encountered',
   DB_ERROR_UNKNOWN_SSCO: 'An unknown SsCo status was encountered',
   DB_ERROR_GEN_FAILURE: 'DIBA error representing ERROR_GEN_FAILURE',
   DB_ERROR_FILE_NOT_FOUND: 'DIBA error representing ERROR_FILE_NOT_FOUND',
   DB_ERROR_MR_MID_NOT_FOUND: 'DIBA error representing ERROR_MR_MID_NOT_FOUND',
   DB_ERROR_ALREADY_EXISTS: 'DIBA error representing ERROR_ALREADY_EXISTS',
   DB_JUVI_ALREADY_PRESENT: 'Newer JUVI Version already present',
   DB_JUVI_INIT_KSDATASTORE_LIB: 'Failed to initilaize the KsDataStore lib',
   DB_JUVI_OPEN_DATASTORE: 'Failed to open data store',
   DB_JUVI_CREATE_DATASTORE: 'Failed to create data store',
   DB_JUVI_UPGRADE_PERFORMED: 'An older version of JUVI was found and was upgraded',
   DB_JUVI_JUVI_IN_USE: 'There is one or more modules in the Multilauncher module store or one or more KISUs still relying on JUVI.',
   DB_JUVI_PAYLOAD_UNSUPPORTED: 'Unsupported installation payload Id',
   DB_JUVI_INVALID_CONFIG: 'Invalid configuration encountered',
   DB_JUVI_INIT_RANDOMIZE: 'Failed to initialize randomization values',
   DB_JUVI_EXPAND_ENVIRONMENT_VARIABLES: 'Failed to expand environment variables',
   DB_KSERROR_BASE: "Base error value for DB_KS_*'s",
   DB_KS_ERROR_DEFAULT: 'DIBA error representing KS_ERROR_DEFAULT',
   DB_KS_ERROR_NOT_SUPPORTED: 'DIBA error representing KS_ERROR_NOT_SUPPORTED',
   DB_KS_ERROR_INVALID_PARAMETER: 'DIBA error representing KS_ERROR_INVALID_PARAMETER',
   DB_KS_ERROR_INVALID_DATA: 'DIBA error representing KS_ERROR_INVALID_DATA',
   DB_KS_ERROR_NOT_ENOUGH_MEMORY: 'DIBA error representing KS_ERROR_NOT_ENOUGH_MEMORY',
   DB_KS_ERROR_EXCEPTION_THROWN: 'DIBA error representing KS_ERROR_EXCEPTION_THROWN',
   DB_KS_ERROR_NOT_INITALIZED: 'DIBA error representing KS_ERROR_NOT_INITALIZED',
   DB_KS_ERROR_SERVICE_NOT_FOUND: 'DIBA error representing KS_ERROR_SERVICE_NOT_FOUND',
   DB_KS_ERROR_EVENT_ERROR: 'DIBA error representing KS_ERROR_EVENT_ERROR',
   DB_KS_ERROR_INVALID_PE_FORMAT: 'DIBA error representing KS_ERROR_INVALID_PE_FORMAT',
   DB_KS_ERROR_RELOCATTING_MODULE: 'DIBA error representing KS_ERROR_RELOCATTING_MODULE',
   DB_KS_ERROR_RESOLVE_IMPORTS: 'DIBA error representing KS_ERROR_RESOLVE_IMPORTS',
   DB_KS_ERROR_OBFUSCATE_PE: 'DIBA error representing KS_ERROR_OBFUSCATE_PE',
   DB_KS_ERROR_DLL_INIT_FAILED: 'DIBA error representing KS_ERROR_DLL_INIT_FAILED',
   DB_KS_ERROR_PROCEDURE_NOT_FOUND: 'DIBA error representing KS_ERROR_PROCEDURE_NOT_FOUND',
   DB_KS_ERROR_INVALID_IMPORT_OF_NON_DLL: 'DIBA error representing KS_ERROR_INVALID_IMPORT_OF_NON_DLL',
   DB_KS_ERROR_FIND_EXPORTED_FUNC: 'DIBA error representing KS_ERROR_FIND_EXPORTED_FUNC',
   DB_KS_ERROR_REMOVE_MODULE: 'DIBA error representing KS_ERROR_REMOVE_MODULE',
   DB_KS_ERROR_MODULE_NOT_FOUND: 'DIBA error representing KS_ERROR_MODULE_NOT_FOUND',
   DB_KS_ERROR_LOAD_SELF_EXCEPTION: 'DIBA error representing KS_ERROR_LOAD_SELF_EXCEPTION',
   DB_KS_ERROR_FAILED_CREATETHREAD: 'DIBA error representing KS_ERROR_FAILED_CREATETHREAD',
   DB_KS_ERROR_UML_IMPORT_OF_ORDINAL: 'DIBA error representing KS_ERROR_UML_IMPORT_OF_ORDINAL',
   DB_KS_ERROR_LOADEDCOUNT_MUTEX: 'DIBA error representing KS_ERROR_LOADEDCOUNT_MUTEX',
   DB_KS_ASBT_RESOURCES_EXHUASTED: 'DIBA error representing KS_ASBT_RESOURCES_EXHUASTED',
   DB_KS_ASBT_WRAPPER_CREATION_FAILED: 'DIBA error representing KS_ASBT_WRAPPER_CREATION_FAILED',
   DB_KS_ASBT_RESOURCES_EXHAUSTED: 'DIBA error representing KS_ASBT_RESOURCES_EXHAUSTED',
   DB_KS_ASBT_VIRTUALALLOC_FAILED: 'DIBA error representing KS_ASBT_VIRTUALALLOC_FAILED',
   DB_KS_ERROR_ALREADY_IN_PROCESS: 'DIBA error representing KS_ERROR_ALREADY_IN_PROCESS',
   DB_KS_ERROR_MODULE_TOO_LARGE: 'DIBA error representing KS_ERROR_MODULE_TOO_LARGE',
   DB_KS_ASBT_TLSALLOC_FAILED: 'DIBA error representing KS_ASBT_TLSALLOC_FAILED',
   DB_KS_EXCEPTION_LOADING_DLL: 'DIBA error representing KS_EXCEPTION_LOADING_DLL',
   DB_KS_ERROR_WRITE_FAILED: 'DIBA error representing KS_ERROR_WRITE_FAILED',
   DB_KS_ERROR_READ_FAILED: 'DIBA error representing KS_ERROR_READ_FAILED',
   DB_KS_ERROR_GEN_FAILURE: 'DIBA error representing ERROR_GEN_FAILURE',
   DB_KS_ERROR_FILE_NOT_FOUND: 'DIBA error representing ERROR_FILE_NOT_FOUND',
   DB_KS_ERROR_MAX_CRASH_COUNT: 'DIBA error representing KS_ERROR_MAX_CRASH_COUNT',
   DB_KS_ERROR_MR_MID_NOT_FOUND: 'DIBA error representing ERROR_MR_MID_NOT_FOUND',
   DB_KS_ERROR_ALREADY_EXISTS: 'DIBA error representing ERROR_ALREADY_EXISTS',
   DB_KS_ERROR_NO_SYSTEM_RESOURCES: 'DIBA error representing ERROR_NO_SYSTEM_RESOURCES',
   DB_CUSTOM_ERROR_BASE: 'Value representing the beginning of the custom NTSTATUS space'
   }