# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
# [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
# Embedded file name: kisu_errors.py
KS_ERROR_MAX_CRASH_COUNT = 4007985153L
KS_USERCOMMS_ERROR_LIB_NOT_INITIALIZED = 4008050689L
KS_USERCOMMS_ERROR_LIB_NATIVE_FUNCTIONS = 4008050690L
KS_USERCOMMS_ERROR_OBJECTINFOVERSION_UNSUPPORTED = 4008050691L
KS_USERCOMMS_ERROR_REMOTEV1_UNSUPPORTED = 4008050692L
KS_USERCOMMS_ERROR_CACHE_UNSUPPORTED = 4008050693L
KS_USERCOMMS_ERROR_LOCAL_V1_NOTLOADED = 4008050703L
KS_USERCOMMS_ERROR_SIGNAL_V1_INVALID = 4008050704L
KS_USERCOMMS_ERROR_SIGNAL_V1_INPROGRESS = 4008050705L
KS_USERCOMMS_ERROR_SIGNAL_V1_ENVIRONMENTVAR = 4008050706L
KS_USERCOMMS_ERROR_SIGNAL_V1_NOTACTIVE = 4008050707L
KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_TIMER = 4008050708L
KS_USERCOMMS_ERROR_SIGNAL_V1_START_TIMER = 4008050709L
KS_USERCOMMS_ERROR_SIGNAL_V1_TIMER_FAILED = 4008050710L
KS_USERCOMMS_ERROR_SIGNAL_V1_OPEN_PROCESS = 4008050711L
KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOGET = 4008050712L
KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOSET = 4008050713L
KS_USERCOMMS_ERROR_SIGNAL_V1_TIMEOUT = 4008050714L
KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_THREAD = 4008050715L
KS_USERCOMMS_ERROR_SIGNAL_V2_INVALID = 4008050720L
KS_USERCOMMS_ERROR_SIGNAL_V2_ENUMERATION = 4008050721L
KS_USERCOMMS_ERROR_SIGNAL_V2_TIMEOUT = 4008050722L
KS_USERCOMMS_ERROR_UNSUPPORTED = 4008050736L
KS_USERCOMMS_ERROR_KS_NOT_INITIALIZED = 4008050737L
KS_USERCOMMS_ERROR_KS_DEFAULT = 4008050738L
KS_USERCOMMS_ERROR_KS_INVALID_PARAMETER = 4008050739L
KS_USERCOMMS_ERROR_KS_INVALID_DATA = 4008050740L
KS_USERCOMMS_ERROR_KS_NOT_ENOUGH_MEMORY = 4008050741L
KS_USERCOMMS_ERROR_KS_EXCEPTION_THROWN = 4008050742L
KS_USERCOMMS_ERROR_KS_INSUFFICIENT_BUFFER = 4008050743L
KS_USERCOMMS_ERROR_KS_SERVICE_NOT_FOUND = 4008050744L
KS_USERCOMMS_ERROR_KS_EVENT_ERROR = 4008050745L
KS_USERCOMMS_ERROR_KS_INVALID_PE_FORMAT = 4008050746L
KS_USERCOMMS_ERROR_KS_RELOCATTING_MODULE = 4008050747L
KS_USERCOMMS_ERROR_KS_RESOLVE_IMPORTS = 4008050748L
KS_USERCOMMS_ERROR_KS_OBFUSCATE_PE = 4008050749L
KS_USERCOMMS_ERROR_KS_DLL_INIT_FAILED = 4008050750L
KS_USERCOMMS_ERROR_KS_PROCEDURE_NOT_FOUND = 4008050751L
KS_USERCOMMS_ERROR_KS_INVALID_IMPORT_OF_NON_DLL = 4008050752L
KS_USERCOMMS_ERROR_KS_FIND_EXPORTED_FUNC = 4008050753L
KS_USERCOMMS_ERROR_KS_REMOVE_MODULE = 4008050754L
KS_USERCOMMS_ERROR_KS_MODULE_NOT_FOUND = 4008050755L
KS_USERCOMMS_ERROR_KS_LOAD_SELF_EXCEPTION = 4008050756L
KS_USERCOMMS_ERROR_KS_FAILED_CREATETHREAD = 4008050757L
KS_USERCOMMS_ERROR_KS_UML_IMPORT_OF_ORDINAL = 4008050758L
KS_USERCOMMS_ERROR_KS_LOADEDCOUNT_MUTEX = 4008050759L
KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHUASTED = 4008050760L
KS_USERCOMMS_ERROR_ASBT_WRAPPER_CREATION_FAILED = 4008050761L
KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHAUSTED = 4008050762L
KS_USERCOMMS_ERROR_KS_ALREADY_IN_PROCESS = 4008050763L
KS_USERCOMMS_ERROR_KS_MODULE_TOO_LARGE = 4008050764L
KS_USERCOMMS_ERROR_ASBT_VIRTUALALLOC_FAILED = 4008050765L
KS_USERCOMMS_ERROR_ASBT_TLSALLOC_FAILED = 4008050766L
KS_USERCOMMS_ERROR_KS_EXCEPTION_LOADING_DLL = 4008050767L
KS_USERCOMMS_ERROR_KS_WRITE_FAILED = 4008050768L
KS_USERCOMMS_ERROR_KS_READ_FAILED = 4008050769L
KS_USERCOMMS_ERROR_INSTANCECACHE_INVALID = 4008050784L
KS_USERCOMMS_ERROR_INSTANCECACHE_DELETED = 4008050785L
KS_USERCOMMS_ERROR_INSTANCECACHE_UNKNOWN = 4008050786L
KS_USERCOMMS_ERROR_INSTANCECACHE_ACQUIRE = 4008050787L
KS_USERCOMMS_ERROR_INSTANCECACHE_RELEASE = 4008050788L
KS_USERCOMMS_ERROR_INSTANCECACHE_CREATE = 4008050789L
KS_USERCOMMS_ERROR_INSTANCECACHE_MARKDESTROY = 4008050790L
KS_USERCOMMS_ERROR_INSTANCECACHE_ADD = 4008050791L
KS_USERCOMMS_ERROR_INSTANCECACHE_REMOVE = 4008050792L
KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_ALREADY_EXISTS = 4008050793L
KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_NOT_FOUND = 4008050794L
KS_USERCOMMS_ERROR_INSTANCECACHE_SYNC = 4008050795L
KS_USERCOMMS_ERROR_INSTANCEENTRY_INVALID = 4008050800L
KS_USERCOMMS_ERROR_INSTANCEENTRY_DELETED = 4008050801L
KS_USERCOMMS_ERROR_INSTANCEENTRY_UNKNOWN = 4008050802L
KS_USERCOMMS_ERROR_INSTANCEENTRY_ACQUIRE = 4008050803L
KS_USERCOMMS_ERROR_INSTANCEENTRY_RELEASE = 4008050804L
KS_USERCOMMS_ERROR_INSTANCEENTRY_CREATE = 4008050805L
KS_USERCOMMS_ERROR_INSTANCEENTRY_MARKDESTROY = 4008050806L
KS_USERCOMMS_ERROR_INSTANCE_INVALID = 4008050816L
KS_USERCOMMS_ERROR_INSTANCE_NOTFOUND = 4008050817L
KS_USERCOMMS_ERROR_INSTANCECACHE_NOTFOUND = 4008050818L
errorStrings = {KS_ERROR_MAX_CRASH_COUNT: 'Max crash count reached',
   KS_USERCOMMS_ERROR_LIB_NOT_INITIALIZED: 'Library is not initialized or is shutting down',
   KS_USERCOMMS_ERROR_LIB_NATIVE_FUNCTIONS: 'Missing required native function',
   KS_USERCOMMS_ERROR_OBJECTINFOVERSION_UNSUPPORTED: 'The objectInfoVersion requested is unsupported with this KISU instance',
   KS_USERCOMMS_ERROR_REMOTEV1_UNSUPPORTED: 'Operations using Remote Version 1 signaling unsupported',
   KS_USERCOMMS_ERROR_CACHE_UNSUPPORTED: 'Operations using the instance cache are unsupported',
   KS_USERCOMMS_ERROR_LOCAL_V1_NOTLOADED: 'Local KISU instance not loaded',
   KS_USERCOMMS_ERROR_SIGNAL_V1_INVALID: 'Signaling to Version 1.x obtained invalid data from the callback',
   KS_USERCOMMS_ERROR_SIGNAL_V1_INPROGRESS: 'Signaling to Version 1.x already in progress by another library',
   KS_USERCOMMS_ERROR_SIGNAL_V1_ENVIRONMENTVAR: 'Environment variable setup failed during signaling to Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_NOTACTIVE: 'Data for signaling to Version 1.x not active',
   KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_TIMER: 'Unable to create timer for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_START_TIMER: 'Unable to start timer for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_TIMER_FAILED: 'Failed to wait on timer for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_OPEN_PROCESS: 'Unable to open process for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOGET: 'Unable to get process information for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_PROCESSINFOSET: 'Unable to set process information for signaling Version 1.x',
   KS_USERCOMMS_ERROR_SIGNAL_V1_TIMEOUT: 'Timed out waiting for a version 1.x callback',
   KS_USERCOMMS_ERROR_SIGNAL_V1_CREATE_THREAD: 'Failed to create a thread for version 1.x signaling',
   KS_USERCOMMS_ERROR_SIGNAL_V2_INVALID: 'Signaling to Version 2.x obtained invalid data',
   KS_USERCOMMS_ERROR_SIGNAL_V2_ENUMERATION: 'Signaling to Version 2.x failed to enumerate list',
   KS_USERCOMMS_ERROR_SIGNAL_V2_TIMEOUT: 'Timed out waiting for a version 2.x callback',
   KS_USERCOMMS_ERROR_UNSUPPORTED: 'Call is unsupported in requested killsuit instance',
   KS_USERCOMMS_ERROR_KS_NOT_INITIALIZED: 'Killsuit instance provided is not initialized',
   KS_USERCOMMS_ERROR_KS_DEFAULT: 'KS_USERCOMMS_ERROR_KS_DEFAULT',
   KS_USERCOMMS_ERROR_KS_INVALID_PARAMETER: 'KS_USERCOMMS_ERROR_KS_INVALID_PARAMETER',
   KS_USERCOMMS_ERROR_KS_INVALID_DATA: 'KS_USERCOMMS_ERROR_KS_INVALID_DATA',
   KS_USERCOMMS_ERROR_KS_NOT_ENOUGH_MEMORY: 'KS_USERCOMMS_ERROR_KS_NOT_ENOUGH_MEMORY',
   KS_USERCOMMS_ERROR_KS_EXCEPTION_THROWN: 'KS_USERCOMMS_ERROR_KS_EXCEPTION_THROWN',
   KS_USERCOMMS_ERROR_KS_INSUFFICIENT_BUFFER: 'KS_USERCOMMS_ERROR_KS_INSUFFICIENT_BUFFER',
   KS_USERCOMMS_ERROR_KS_SERVICE_NOT_FOUND: 'KS_USERCOMMS_ERROR_KS_SERVICE_NOT_FOUND',
   KS_USERCOMMS_ERROR_KS_EVENT_ERROR: 'KS_USERCOMMS_ERROR_KS_EVENT_ERROR',
   KS_USERCOMMS_ERROR_KS_INVALID_PE_FORMAT: 'KS_USERCOMMS_ERROR_KS_INVALID_PE_FORMAT',
   KS_USERCOMMS_ERROR_KS_RELOCATTING_MODULE: 'KS_USERCOMMS_ERROR_KS_RELOCATTING_MODULE',
   KS_USERCOMMS_ERROR_KS_RESOLVE_IMPORTS: 'KS_USERCOMMS_ERROR_KS_RESOLVE_IMPORTS',
   KS_USERCOMMS_ERROR_KS_OBFUSCATE_PE: 'KS_USERCOMMS_ERROR_KS_OBFUSCATE_PE',
   KS_USERCOMMS_ERROR_KS_DLL_INIT_FAILED: 'KS_USERCOMMS_ERROR_KS_DLL_INIT_FAILED',
   KS_USERCOMMS_ERROR_KS_PROCEDURE_NOT_FOUND: 'KS_USERCOMMS_ERROR_KS_PROCEDURE_NOT_FOUND',
   KS_USERCOMMS_ERROR_KS_INVALID_IMPORT_OF_NON_DLL: 'KS_USERCOMMS_ERROR_KS_INVALID_IMPORT_OF_NON_DLL',
   KS_USERCOMMS_ERROR_KS_FIND_EXPORTED_FUNC: 'KS_USERCOMMS_ERROR_KS_FIND_EXPORTED_FUNC',
   KS_USERCOMMS_ERROR_KS_REMOVE_MODULE: 'KS_USERCOMMS_ERROR_KS_REMOVE_MODULE',
   KS_USERCOMMS_ERROR_KS_MODULE_NOT_FOUND: 'KS_USERCOMMS_ERROR_KS_MODULE_NOT_FOUND',
   KS_USERCOMMS_ERROR_KS_LOAD_SELF_EXCEPTION: 'KS_USERCOMMS_ERROR_KS_LOAD_SELF_EXCEPTION',
   KS_USERCOMMS_ERROR_KS_FAILED_CREATETHREAD: 'KS_USERCOMMS_ERROR_KS_FAILED_CREATETHREAD',
   KS_USERCOMMS_ERROR_KS_UML_IMPORT_OF_ORDINAL: 'KS_USERCOMMS_ERROR_KS_UML_IMPORT_OF_ORDINAL',
   KS_USERCOMMS_ERROR_KS_LOADEDCOUNT_MUTEX: 'KS_USERCOMMS_ERROR_KS_LOADEDCOUNT_MUTEX',
   KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHUASTED: 'KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHUASTED',
   KS_USERCOMMS_ERROR_ASBT_WRAPPER_CREATION_FAILED: 'KS_USERCOMMS_ERROR_ASBT_WRAPPER_CREATION_FAILED',
   KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHAUSTED: 'KS_USERCOMMS_ERROR_ASBT_RESOURCES_EXHAUSTED',
   KS_USERCOMMS_ERROR_KS_ALREADY_IN_PROCESS: 'KS_USERCOMMS_ERROR_KS_ALREADY_IN_PROCESS',
   KS_USERCOMMS_ERROR_KS_MODULE_TOO_LARGE: 'KS_USERCOMMS_ERROR_KS_MODULE_TOO_LARGE',
   KS_USERCOMMS_ERROR_ASBT_VIRTUALALLOC_FAILED: 'KS_USERCOMMS_ERROR_ASBT_VIRTUALALLOC_FAILED',
   KS_USERCOMMS_ERROR_ASBT_TLSALLOC_FAILED: 'KS_USERCOMMS_ERROR_ASBT_TLSALLOC_FAILED',
   KS_USERCOMMS_ERROR_KS_EXCEPTION_LOADING_DLL: 'KS_USERCOMMS_ERROR_KS_EXCEPTION_LOADING_DLL',
   KS_USERCOMMS_ERROR_KS_WRITE_FAILED: 'KS_USERCOMMS_ERROR_KS_WRITE_FAILED',
   KS_USERCOMMS_ERROR_KS_READ_FAILED: 'KS_USERCOMMS_ERROR_KS_READ_FAILED',
   KS_USERCOMMS_ERROR_INSTANCECACHE_INVALID: 'Instance cache is invalid',
   KS_USERCOMMS_ERROR_INSTANCECACHE_DELETED: 'Instance cache is marked for deletion',
   KS_USERCOMMS_ERROR_INSTANCECACHE_UNKNOWN: 'Instance cache is an unknown version',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ACQUIRE: 'Failed to acquire reference to instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_RELEASE: 'Failed to release reference to instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_CREATE: 'Failed to create instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_MARKDESTROY: 'Failed to mark instance cache for destruction',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ADD: 'Failed to add to the instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_REMOVE: 'Failed to remove from the instance cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_ALREADY_EXISTS: 'Entry already existing in the specified cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_ENTRY_NOT_FOUND: 'Entry not found in the specified cache',
   KS_USERCOMMS_ERROR_INSTANCECACHE_SYNC: 'Failed to acquire synchronization object of cache',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_INVALID: 'Instance entry is invalid',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_DELETED: 'Instance entry is marked for deletion',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_UNKNOWN: 'Instance entry is an unknown version',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_ACQUIRE: 'Failed to acquire reference to instance entry',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_RELEASE: 'Failed to release reference to instance entry',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_CREATE: 'Failed to create instance entry',
   KS_USERCOMMS_ERROR_INSTANCEENTRY_MARKDESTROY: 'Failed to mark instance entry for destruction',
   KS_USERCOMMS_ERROR_INSTANCE_INVALID: 'The given instance is invalid',
   KS_USERCOMMS_ERROR_INSTANCE_NOTFOUND: 'Instance not found',
   KS_USERCOMMS_ERROR_INSTANCECACHE_NOTFOUND: 'Instance cache not found'
   }