# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
# [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
# Embedded file name: Tkconstants.py
NO = FALSE = OFF = 0
YES = TRUE = ON = 1
N = 'n'
S = 's'
W = 'w'
E = 'e'
NW = 'nw'
SW = 'sw'
NE = 'ne'
SE = 'se'
NS = 'ns'
EW = 'ew'
NSEW = 'nsew'
CENTER = 'center'
NONE = 'none'
X = 'x'
Y = 'y'
BOTH = 'both'
LEFT = 'left'
TOP = 'top'
RIGHT = 'right'
BOTTOM = 'bottom'
RAISED = 'raised'
SUNKEN = 'sunken'
FLAT = 'flat'
RIDGE = 'ridge'
GROOVE = 'groove'
SOLID = 'solid'
HORIZONTAL = 'horizontal'
VERTICAL = 'vertical'
NUMERIC = 'numeric'
CHAR = 'char'
WORD = 'word'
BASELINE = 'baseline'
INSIDE = 'inside'
OUTSIDE = 'outside'
SEL = 'sel'
SEL_FIRST = 'sel.first'
SEL_LAST = 'sel.last'
END = 'end'
INSERT = 'insert'
CURRENT = 'current'
ANCHOR = 'anchor'
ALL = 'all'
NORMAL = 'normal'
DISABLED = 'disabled'
ACTIVE = 'active'
HIDDEN = 'hidden'
CASCADE = 'cascade'
CHECKBUTTON = 'checkbutton'
COMMAND = 'command'
RADIOBUTTON = 'radiobutton'
SEPARATOR = 'separator'
SINGLE = 'single'
BROWSE = 'browse'
MULTIPLE = 'multiple'
EXTENDED = 'extended'
DOTBOX = 'dotbox'
UNDERLINE = 'underline'
PIESLICE = 'pieslice'
CHORD = 'chord'
ARC = 'arc'
FIRST = 'first'
LAST = 'last'
BUTT = 'butt'
PROJECTING = 'projecting'
ROUND = 'round'
BEVEL = 'bevel'
MITER = 'miter'
MOVETO = 'moveto'
SCROLL = 'scroll'
UNITS = 'units'
PAGES = 'pages'